/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dns/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listZones"];
        put?: never;
        /** @description Creates the zone in PowerDNS then locally (compensated on local failure). duplicate when the name is taken, overlaps another tenant's zone or already exists in PowerDNS (the owner is never revealed). */
        post: operations["createZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/zones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getZone"];
        put: operations["updateZone"];
        post?: never;
        delete: operations["deleteZone"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/zones/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportZone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/zones/{id}/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description master/producer zones only; any other kind is invalid_kind. */
        post: operations["notifyZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/zones/{id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecords"];
        /** @description keyed by the original (name, type); a rename is REPLACE new + DELETE old in one PATCH. */
        put: operations["updateRecordSet"];
        /** @description REPLACE of (name, type) with all values. */
        post: operations["upsertRecordSet"];
        delete: operations["deleteRecordSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTemplates"];
        put?: never;
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplate"];
        /** @description replaces the record list. */
        put: operations["updateTemplate"];
        post?: never;
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/supermasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSupermasters"];
        put?: never;
        /** @description platform-admin only; the PowerDNS account is forced to the tenant. */
        post: operations["createSupermaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/supermasters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSupermaster"];
        put?: never;
        post?: never;
        /** @description platform-admin only. */
        delete: operations["deleteSupermaster"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getServerConfig"];
        /** @description Validates, persists, renders the managed include files and restarts only the container whose file changed (restart_required when the restarter is disabled). A no-op save restarts nothing. */
        put: operations["updateServerConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Runs the fixed resolver/authoritative panel catalogue over the window (step 60 s / 300 s / 900 s). No query text is accepted: any parameter other than window is refused. available=false when no metrics endpoint is configured. */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Long-lived SSE stream of this tenant's dns.* events. The route timeout is raised to the gateway's 5-minute maximum; the module closes the stream at 290 s and the client resumes with last_id. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Schema-versioned export of zone metadata, templates and supermasters (plus BIND text of each zone for reference). Never carries API keys. Another tenant than the caller's is platform-admin only. */
        post: operations["exportBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Loads a backup into the caller's tenant (skip keeps existing rows, overwrite rewrites them); zones are re-linked when present in PowerDNS and not owned elsewhere, missing ones are reported. tenant_id other than the caller's or full is platform-admin only. */
        post: operations["importBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dns/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description bad_request | invalid_name | invalid_record | invalid_kind | invalid_config | zone_not_found | record_not_found | template_not_found | duplicate | conflict | forbidden | pdns_unavailable | metrics_unavailable | unauthenticated | not_found | validation_failed | malformed_body | body_too_large | temporarily_unavailable | not_implemented */
            reason?: string;
            detail?: Record<string, never>;
        };
        /** @enum {string} */
        ZoneKind: "native" | "master" | "slave" | "producer" | "consumer";
        /** @enum {string} */
        ZoneOrigin: "manual" | "ipam";
        /** @enum {string} */
        EditableType: "A" | "AAAA" | "CNAME" | "MX" | "NS" | "PTR" | "SRV" | "TXT" | "CAA" | "DS" | "DNSKEY" | "TLSA" | "SSHFP" | "SPF" | "NAPTR";
        Zone: {
            id: string;
            /** @description canonical: lower-case, trailing dot, A-labels */
            name: string;
            kind: components["schemas"]["ZoneKind"];
            masters: string[];
            dnssec: boolean;
            description?: string;
            template_id?: string;
            origin: components["schemas"]["ZoneOrigin"];
            nameservers?: string[];
            created_by?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ZoneDetail: components["schemas"]["Zone"] & {
            /** @description from PowerDNS */
            serial?: number;
            /** @description from PowerDNS */
            notified_serial?: number;
        };
        ZonePage: {
            items: components["schemas"]["Zone"][];
            total: number;
        };
        ZoneCreate: {
            name: string;
            kind: components["schemas"]["ZoneKind"];
            masters?: string[];
            nameservers?: string[];
            dnssec?: boolean;
            description?: string;
            template_id?: string;
        };
        ZoneUpdate: {
            kind?: components["schemas"]["ZoneKind"];
            masters?: string[];
            dnssec?: boolean;
            description?: string;
        };
        ZoneExport: {
            zone: string;
            /** @description BIND zone text (size-capped) */
            text: string;
        };
        RecordValue: {
            content: string;
            disabled?: boolean;
        };
        RecordSetInput: {
            /** @description "@" | relative | absolute (trailing dot) */
            name: string;
            type: components["schemas"]["EditableType"];
            ttl: number;
            values: components["schemas"]["RecordValue"][];
            comment?: string;
        };
        RecordSet: {
            /** @description qualified owner name */
            name: string;
            type: string;
            ttl: number;
            values: {
                content: string;
                disabled: boolean;
            }[];
            comment?: string;
            /** @description true for SOA */
            read_only: boolean;
        };
        RecordPage: {
            items: components["schemas"]["RecordSet"][];
            total: number;
        };
        RecordUpdate: {
            original: {
                name: string;
                type: components["schemas"]["EditableType"];
            };
            record: components["schemas"]["RecordSetInput"];
        };
        TemplateRecord: {
            /** @description may contain [ZONE]; "@" or empty = apex */
            name: string;
            type: components["schemas"]["EditableType"];
            ttl: number;
            /** @description may contain [ZONE] */
            content: string;
            /** @description MX/SRV */
            priority?: number;
        };
        TemplateInput: {
            name: string;
            description?: string;
            records: components["schemas"]["TemplateRecord"][];
        };
        Template: {
            id: string;
            name: string;
            description?: string;
            records: components["schemas"]["TemplateRecord"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TemplateList: {
            items: components["schemas"]["Template"][];
        };
        SupermasterInput: {
            ip: string;
            nameserver: string;
        };
        Supermaster: {
            id: string;
            ip: string;
            nameserver: string;
            created_by?: string;
            /** Format: date-time */
            created_at: string;
        };
        SupermasterList: {
            items: components["schemas"]["Supermaster"][];
        };
        RecursorSettings: {
            listen_addresses: string[];
            port: number;
            allowed_networks: string[];
            upstream_resolvers: string[];
            /** @enum {string} */
            dnssec_validation: "off" | "process" | "validate";
            allow_open_resolver?: boolean;
        };
        AuthoritativeSettings: {
            listen_addresses: string[];
            port: number;
            transfer_peers: string[];
        };
        ServerConfigInput: {
            recursor: components["schemas"]["RecursorSettings"];
            authoritative: components["schemas"]["AuthoritativeSettings"];
        };
        ServerConfig: {
            recursor: components["schemas"]["RecursorSettings"];
            authoritative: components["schemas"]["AuthoritativeSettings"];
            /** @description true when nothing was saved yet */
            defaults: boolean;
            restarter: {
                enabled: boolean;
                containers: {
                    auth?: string;
                    recursor?: string;
                };
            };
        };
        ConfigResult: {
            recursor: components["schemas"]["RecursorSettings"];
            authoritative: components["schemas"]["AuthoritativeSettings"];
            changed: ("recursor" | "authoritative")[];
            restarted: string[];
            restart_required: string[];
            errors: {
                /** @enum {string} */
                server?: "recursor" | "authoritative";
                reason?: string;
            }[];
        };
        Dashboard: {
            available: boolean;
            /** @enum {string} */
            window: "1h" | "6h" | "24h";
            step_seconds?: number;
            panels?: {
                /** @description fixed catalogue id */
                id: string;
                /** @enum {string} */
                kind: "stat" | "series";
                unit?: string;
                /** @description stat panels; absent when there is no data */
                value?: number;
                /** @description this panel's queries failed (the others are unaffected) */
                unavailable?: boolean;
                series?: {
                    labels?: {
                        [key: string]: string;
                    };
                    points?: number[][];
                }[];
            }[];
        };
    };
    responses: {
        /** @description refusal */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        csrf: string;
        /** @example 018f3a2b-0000-7000-8000-000000000001 */
        id: string;
        page: number;
        pageSize: number;
        recordPageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listZones: {
        parameters: {
            query?: {
                query?: string;
                kind?: components["schemas"]["ZoneKind"];
                origin?: components["schemas"]["ZoneOrigin"];
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description zones (name order) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonePage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createZone: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneCreate"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description zone + serials from PowerDNS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateZone: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneUpdate"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteZone: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted from PowerDNS, the resolver forward and locally */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    exportZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description BIND zone text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneExport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    notifyZone: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NOTIFY queued by PowerDNS */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listRecords: {
        parameters: {
            query?: {
                type?: string;
                query?: string;
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["recordPageSize"];
            };
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description record sets (name, type order); SOA read_only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateRecordSet: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordUpdate"];
            };
        };
        responses: {
            /** @description record set written */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSet"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    upsertRecordSet: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSetInput"];
            };
        };
        responses: {
            /** @description record set written */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSet"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRecordSet: {
        parameters: {
            query: {
                name: string;
                type: components["schemas"]["EditableType"];
            };
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description templates (name order) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateInput"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted (zones created from it are kept) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listSupermasters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description this tenant's supermasters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupermasterList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSupermaster: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupermasterInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supermaster"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSupermaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description supermaster */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supermaster"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteSupermaster: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getServerConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current (or default) configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerConfig"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateServerConfig: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerConfigInput"];
            };
        };
        responses: {
            /** @description saved and applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                window?: "1h" | "6h" | "24h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description fixed panel set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                last_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of this tenant's DNS events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description platform-admin only when not the caller's tenant
                     */
                    tenant_id?: string;
                };
            };
        };
        responses: {
            /** @description tenant export (no keys) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    mode?: "skip" | "overwrite";
                    /** Format: uuid */
                    tenant_id?: string;
                    full?: boolean;
                    backup: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description import summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tenant_id?: string;
                        mode?: string;
                        imported?: {
                            [key: string]: number;
                        };
                        skipped?: {
                            [key: string]: number;
                        };
                        missing_in_pdns?: string[];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description liveness + component status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
