// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dns/v1/dns.proto

// dns.v1 is the module-to-module API of the DNS module (contracts §B). It is
// NOT proxied by the gateway: callers are authenticated platform services on
// the Freya SPIFFE mTLS channel, checked against the policy allow-list.
//
//   - Challenges publishes and removes ACME DNS-01 `_acme-challenge` TXT values
//     for the certificate service (lcm) ONLY: the policy allows just the lcm
//     identity AND the handler re-checks the peer SPIFFE ID.
//   - Zones is a read-only view of the managed zones of the tenant named in
//     each request, for any platform module.
//
// No message ever carries PowerDNS/recursor API keys, record values beyond the
// challenge token, or configuration file contents.

package dnsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"` // the certificate identifier (may start with "*.")
	Fqdn          string                 `protobuf:"bytes,3,opt,name=fqdn,proto3" json:"fqdn,omitempty"`     // must equal "_acme-challenge." + domain without "*."
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`   // 43-char base64url key authorization digest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_dns_v1_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChallengeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChallengeRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *ChallengeRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"` // the zone the value was written to / cleaned from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_dns_v1_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

// Timestamp is seconds since the epoch; 0 = unset.
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unix          int64                  `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_dns_v1_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{2}
}

func (x *Timestamp) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // canonical, trailing dot
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // native | master | slave | producer | consumer
	Dnssec        bool                   `protobuf:"varint,4,opt,name=dnssec,proto3" json:"dnssec,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"` // manual | ipam
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Masters       []string               `protobuf:"bytes,7,rep,name=masters,proto3" json:"masters,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *Timestamp             `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_dns_v1_dns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{3}
}

func (x *Zone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Zone) GetDnssec() bool {
	if x != nil {
		return x.Dnssec
	}
	return false
}

func (x *Zone) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Zone) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Zone) GetMasters() []string {
	if x != nil {
		return x.Masters
	}
	return nil
}

func (x *Zone) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Zone) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                        // name substring
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 1-based
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // <= 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesRequest) Reset() {
	*x = ListZonesRequest{}
	mi := &file_dns_v1_dns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesRequest) ProtoMessage() {}

func (x *ListZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesRequest.ProtoReflect.Descriptor instead.
func (*ListZonesRequest) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{4}
}

func (x *ListZonesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListZonesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListZonesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListZonesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Zone                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesResponse) Reset() {
	*x = ListZonesResponse{}
	mi := &file_dns_v1_dns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesResponse) ProtoMessage() {}

func (x *ListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesResponse.ProtoReflect.Descriptor instead.
func (*ListZonesResponse) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{5}
}

func (x *ListZonesResponse) GetItems() []*Zone {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListZonesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`     // either id ...
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // ... or the zone name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneRequest) Reset() {
	*x = GetZoneRequest{}
	mi := &file_dns_v1_dns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneRequest) ProtoMessage() {}

func (x *GetZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneRequest.ProtoReflect.Descriptor instead.
func (*GetZoneRequest) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{6}
}

func (x *GetZoneRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindForNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // a FQDN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindForNameRequest) Reset() {
	*x = FindForNameRequest{}
	mi := &file_dns_v1_dns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindForNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindForNameRequest) ProtoMessage() {}

func (x *FindForNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_v1_dns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindForNameRequest.ProtoReflect.Descriptor instead.
func (*FindForNameRequest) Descriptor() ([]byte, []int) {
	return file_dns_v1_dns_proto_rawDescGZIP(), []int{7}
}

func (x *FindForNameRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FindForNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dns_v1_dns_proto protoreflect.FileDescriptor

const file_dns_v1_dns_proto_rawDesc = "" +
	"\n" +
	"\x10dns/v1/dns.proto\x12\x06dns.v1\"q\n" +
	"\x10ChallengeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04fqdn\x18\x03 \x01(\tR\x04fqdn\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"'\n" +
	"\x11ChallengeResponse\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\"\x1f\n" +
	"\tTimestamp\x12\x12\n" +
	"\x04unix\x18\x01 \x01(\x03R\x04unix\"\x8e\x02\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06dnssec\x18\x04 \x01(\bR\x06dnssec\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\amasters\x18\a \x03(\tR\amasters\x120\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x11.dns.v1.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x11.dns.v1.TimestampR\tupdatedAt\"v\n" +
	"\x10ListZonesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"M\n" +
	"\x11ListZonesResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.dns.v1.ZoneR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"Q\n" +
	"\x0eGetZoneRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"E\n" +
	"\x12FindForNameRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x8c\x01\n" +
	"\n" +
	"Challenges\x12>\n" +
	"\aPresent\x12\x18.dns.v1.ChallengeRequest\x1a\x19.dns.v1.ChallengeResponse\x12>\n" +
	"\aCleanUp\x12\x18.dns.v1.ChallengeRequest\x1a\x19.dns.v1.ChallengeResponse2\xaa\x01\n" +
	"\x05Zones\x12;\n" +
	"\x04List\x12\x18.dns.v1.ListZonesRequest\x1a\x19.dns.v1.ListZonesResponse\x12+\n" +
	"\x03Get\x12\x16.dns.v1.GetZoneRequest\x1a\f.dns.v1.Zone\x127\n" +
	"\vFindForName\x12\x1a.dns.v1.FindForNameRequest\x1a\f.dns.v1.ZoneB?Z=github.com/go-freya/freya/services/dns/api/proto/dns/v1;dnsv1b\x06proto3"

var (
	file_dns_v1_dns_proto_rawDescOnce sync.Once
	file_dns_v1_dns_proto_rawDescData []byte
)

func file_dns_v1_dns_proto_rawDescGZIP() []byte {
	file_dns_v1_dns_proto_rawDescOnce.Do(func() {
		file_dns_v1_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_v1_dns_proto_rawDesc), len(file_dns_v1_dns_proto_rawDesc)))
	})
	return file_dns_v1_dns_proto_rawDescData
}

var file_dns_v1_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dns_v1_dns_proto_goTypes = []any{
	(*ChallengeRequest)(nil),   // 0: dns.v1.ChallengeRequest
	(*ChallengeResponse)(nil),  // 1: dns.v1.ChallengeResponse
	(*Timestamp)(nil),          // 2: dns.v1.Timestamp
	(*Zone)(nil),               // 3: dns.v1.Zone
	(*ListZonesRequest)(nil),   // 4: dns.v1.ListZonesRequest
	(*ListZonesResponse)(nil),  // 5: dns.v1.ListZonesResponse
	(*GetZoneRequest)(nil),     // 6: dns.v1.GetZoneRequest
	(*FindForNameRequest)(nil), // 7: dns.v1.FindForNameRequest
}
var file_dns_v1_dns_proto_depIdxs = []int32{
	2, // 0: dns.v1.Zone.created_at:type_name -> dns.v1.Timestamp
	2, // 1: dns.v1.Zone.updated_at:type_name -> dns.v1.Timestamp
	3, // 2: dns.v1.ListZonesResponse.items:type_name -> dns.v1.Zone
	0, // 3: dns.v1.Challenges.Present:input_type -> dns.v1.ChallengeRequest
	0, // 4: dns.v1.Challenges.CleanUp:input_type -> dns.v1.ChallengeRequest
	4, // 5: dns.v1.Zones.List:input_type -> dns.v1.ListZonesRequest
	6, // 6: dns.v1.Zones.Get:input_type -> dns.v1.GetZoneRequest
	7, // 7: dns.v1.Zones.FindForName:input_type -> dns.v1.FindForNameRequest
	1, // 8: dns.v1.Challenges.Present:output_type -> dns.v1.ChallengeResponse
	1, // 9: dns.v1.Challenges.CleanUp:output_type -> dns.v1.ChallengeResponse
	5, // 10: dns.v1.Zones.List:output_type -> dns.v1.ListZonesResponse
	3, // 11: dns.v1.Zones.Get:output_type -> dns.v1.Zone
	3, // 12: dns.v1.Zones.FindForName:output_type -> dns.v1.Zone
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dns_v1_dns_proto_init() }
func file_dns_v1_dns_proto_init() {
	if File_dns_v1_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_v1_dns_proto_rawDesc), len(file_dns_v1_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dns_v1_dns_proto_goTypes,
		DependencyIndexes: file_dns_v1_dns_proto_depIdxs,
		MessageInfos:      file_dns_v1_dns_proto_msgTypes,
	}.Build()
	File_dns_v1_dns_proto = out.File
	file_dns_v1_dns_proto_goTypes = nil
	file_dns_v1_dns_proto_depIdxs = nil
}
