// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: dns/v1/dns.proto

// dns.v1 is the module-to-module API of the DNS module (contracts §B). It is
// NOT proxied by the gateway: callers are authenticated platform services on
// the Freya SPIFFE mTLS channel, checked against the policy allow-list.
//
//   - Challenges publishes and removes ACME DNS-01 `_acme-challenge` TXT values
//     for the certificate service (lcm) ONLY: the policy allows just the lcm
//     identity AND the handler re-checks the peer SPIFFE ID.
//   - Zones is a read-only view of the managed zones of the tenant named in
//     each request, for any platform module.
//
// No message ever carries PowerDNS/recursor API keys, record values beyond the
// challenge token, or configuration file contents.

package dnsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Challenges_Present_FullMethodName = "/dns.v1.Challenges/Present"
	Challenges_CleanUp_FullMethodName = "/dns.v1.Challenges/CleanUp"
)

// ChallengesClient is the client API for Challenges service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Challenges is the lcm-only ACME DNS-01 surface.
type ChallengesClient interface {
	// Present adds value to the TXT rrset at fqdn (idempotent).
	Present(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	// CleanUp removes value from the TXT rrset at fqdn (absent value = OK).
	CleanUp(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
}

type challengesClient struct {
	cc grpc.ClientConnInterface
}

func NewChallengesClient(cc grpc.ClientConnInterface) ChallengesClient {
	return &challengesClient{cc}
}

func (c *challengesClient) Present(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, Challenges_Present_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengesClient) CleanUp(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, Challenges_CleanUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChallengesServer is the server API for Challenges service.
// All implementations must embed UnimplementedChallengesServer
// for forward compatibility.
//
// Challenges is the lcm-only ACME DNS-01 surface.
type ChallengesServer interface {
	// Present adds value to the TXT rrset at fqdn (idempotent).
	Present(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	// CleanUp removes value from the TXT rrset at fqdn (absent value = OK).
	CleanUp(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	mustEmbedUnimplementedChallengesServer()
}

// UnimplementedChallengesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChallengesServer struct{}

func (UnimplementedChallengesServer) Present(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Present not implemented")
}
func (UnimplementedChallengesServer) CleanUp(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanUp not implemented")
}
func (UnimplementedChallengesServer) mustEmbedUnimplementedChallengesServer() {}
func (UnimplementedChallengesServer) testEmbeddedByValue()                    {}

// UnsafeChallengesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChallengesServer will
// result in compilation errors.
type UnsafeChallengesServer interface {
	mustEmbedUnimplementedChallengesServer()
}

func RegisterChallengesServer(s grpc.ServiceRegistrar, srv ChallengesServer) {
	// If the following call panics, it indicates UnimplementedChallengesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Challenges_ServiceDesc, srv)
}

func _Challenges_Present_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengesServer).Present(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Challenges_Present_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengesServer).Present(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Challenges_CleanUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengesServer).CleanUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Challenges_CleanUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengesServer).CleanUp(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Challenges_ServiceDesc is the grpc.ServiceDesc for Challenges service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Challenges_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.v1.Challenges",
	HandlerType: (*ChallengesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Present",
			Handler:    _Challenges_Present_Handler,
		},
		{
			MethodName: "CleanUp",
			Handler:    _Challenges_CleanUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns/v1/dns.proto",
}

const (
	Zones_List_FullMethodName        = "/dns.v1.Zones/List"
	Zones_Get_FullMethodName         = "/dns.v1.Zones/Get"
	Zones_FindForName_FullMethodName = "/dns.v1.Zones/FindForName"
)

// ZonesClient is the client API for Zones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Zones is the read-only module view of a tenant's managed zones.
type ZonesClient interface {
	List(ctx context.Context, in *ListZonesRequest, opts ...grpc.CallOption) (*ListZonesResponse, error)
	Get(ctx context.Context, in *GetZoneRequest, opts ...grpc.CallOption) (*Zone, error)
	// FindForName returns the tenant's longest managed zone containing name.
	FindForName(ctx context.Context, in *FindForNameRequest, opts ...grpc.CallOption) (*Zone, error)
}

type zonesClient struct {
	cc grpc.ClientConnInterface
}

func NewZonesClient(cc grpc.ClientConnInterface) ZonesClient {
	return &zonesClient{cc}
}

func (c *zonesClient) List(ctx context.Context, in *ListZonesRequest, opts ...grpc.CallOption) (*ListZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZonesResponse)
	err := c.cc.Invoke(ctx, Zones_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zonesClient) Get(ctx context.Context, in *GetZoneRequest, opts ...grpc.CallOption) (*Zone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Zone)
	err := c.cc.Invoke(ctx, Zones_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zonesClient) FindForName(ctx context.Context, in *FindForNameRequest, opts ...grpc.CallOption) (*Zone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Zone)
	err := c.cc.Invoke(ctx, Zones_FindForName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZonesServer is the server API for Zones service.
// All implementations must embed UnimplementedZonesServer
// for forward compatibility.
//
// Zones is the read-only module view of a tenant's managed zones.
type ZonesServer interface {
	List(context.Context, *ListZonesRequest) (*ListZonesResponse, error)
	Get(context.Context, *GetZoneRequest) (*Zone, error)
	// FindForName returns the tenant's longest managed zone containing name.
	FindForName(context.Context, *FindForNameRequest) (*Zone, error)
	mustEmbedUnimplementedZonesServer()
}

// UnimplementedZonesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZonesServer struct{}

func (UnimplementedZonesServer) List(context.Context, *ListZonesRequest) (*ListZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedZonesServer) Get(context.Context, *GetZoneRequest) (*Zone, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedZonesServer) FindForName(context.Context, *FindForNameRequest) (*Zone, error) {
	return nil, status.Error(codes.Unimplemented, "method FindForName not implemented")
}
func (UnimplementedZonesServer) mustEmbedUnimplementedZonesServer() {}
func (UnimplementedZonesServer) testEmbeddedByValue()               {}

// UnsafeZonesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZonesServer will
// result in compilation errors.
type UnsafeZonesServer interface {
	mustEmbedUnimplementedZonesServer()
}

func RegisterZonesServer(s grpc.ServiceRegistrar, srv ZonesServer) {
	// If the following call panics, it indicates UnimplementedZonesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Zones_ServiceDesc, srv)
}

func _Zones_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZonesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zones_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZonesServer).List(ctx, req.(*ListZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zones_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZonesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zones_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZonesServer).Get(ctx, req.(*GetZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zones_FindForName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindForNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZonesServer).FindForName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zones_FindForName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZonesServer).FindForName(ctx, req.(*FindForNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zones_ServiceDesc is the grpc.ServiceDesc for Zones service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zones_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.v1.Zones",
	HandlerType: (*ZonesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Zones_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Zones_Get_Handler,
		},
		{
			MethodName: "FindForName",
			Handler:    _Zones_FindForName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns/v1/dns.proto",
}
