// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-dns/internal/data/ent/dnsconfig"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/supermaster"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zone"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zonetemplate"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dnsconfigFields := schema.DnsConfig{}.Fields()
	_ = dnsconfigFields
	// dnsconfigDescID is the schema descriptor for id field.
	dnsconfigDescID := dnsconfigFields[0].Descriptor()
	// dnsconfig.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dnsconfig.IDValidator = dnsconfigDescID.Validators[0].(func(string) error)
	supermasterMixin := schema.Supermaster{}.Mixin()
	supermaster.Policy = privacy.NewPolicies(supermasterMixin[2], schema.Supermaster{})
	supermaster.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := supermaster.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	supermasterMixinFields2 := supermasterMixin[2].Fields()
	_ = supermasterMixinFields2
	supermasterFields := schema.Supermaster{}.Fields()
	_ = supermasterFields
	// supermasterDescTenantID is the schema descriptor for tenant_id field.
	supermasterDescTenantID := supermasterMixinFields2[0].Descriptor()
	// supermaster.DefaultTenantID holds the default value on creation for the tenant_id field.
	supermaster.DefaultTenantID = supermasterDescTenantID.Default.(uint32)
	// supermasterDescIP is the schema descriptor for ip field.
	supermasterDescIP := supermasterFields[1].Descriptor()
	// supermaster.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	supermaster.IPValidator = func() func(string) error {
		validators := supermasterDescIP.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ip string) error {
			for _, fn := range fns {
				if err := fn(ip); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// supermasterDescNameserver is the schema descriptor for nameserver field.
	supermasterDescNameserver := supermasterFields[2].Descriptor()
	// supermaster.NameserverValidator is a validator for the "nameserver" field. It is called by the builders before save.
	supermaster.NameserverValidator = func() func(string) error {
		validators := supermasterDescNameserver.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(nameserver string) error {
			for _, fn := range fns {
				if err := fn(nameserver); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// supermasterDescAccount is the schema descriptor for account field.
	supermasterDescAccount := supermasterFields[3].Descriptor()
	// supermaster.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	supermaster.AccountValidator = supermasterDescAccount.Validators[0].(func(string) error)
	// supermasterDescID is the schema descriptor for id field.
	supermasterDescID := supermasterFields[0].Descriptor()
	// supermaster.IDValidator is a validator for the "id" field. It is called by the builders before save.
	supermaster.IDValidator = supermasterDescID.Validators[0].(func(string) error)
	zoneMixin := schema.Zone{}.Mixin()
	zone.Policy = privacy.NewPolicies(zoneMixin[2], schema.Zone{})
	zone.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := zone.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	zoneMixinFields2 := zoneMixin[2].Fields()
	_ = zoneMixinFields2
	zoneFields := schema.Zone{}.Fields()
	_ = zoneFields
	// zoneDescTenantID is the schema descriptor for tenant_id field.
	zoneDescTenantID := zoneMixinFields2[0].Descriptor()
	// zone.DefaultTenantID holds the default value on creation for the tenant_id field.
	zone.DefaultTenantID = zoneDescTenantID.Default.(uint32)
	// zoneDescPdnsID is the schema descriptor for pdns_id field.
	zoneDescPdnsID := zoneFields[1].Descriptor()
	// zone.PdnsIDValidator is a validator for the "pdns_id" field. It is called by the builders before save.
	zone.PdnsIDValidator = func() func(string) error {
		validators := zoneDescPdnsID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(pdns_id string) error {
			for _, fn := range fns {
				if err := fn(pdns_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// zoneDescName is the schema descriptor for name field.
	zoneDescName := zoneFields[2].Descriptor()
	// zone.NameValidator is a validator for the "name" field. It is called by the builders before save.
	zone.NameValidator = func() func(string) error {
		validators := zoneDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// zoneDescMasters is the schema descriptor for masters field.
	zoneDescMasters := zoneFields[4].Descriptor()
	// zone.MastersValidator is a validator for the "masters" field. It is called by the builders before save.
	zone.MastersValidator = zoneDescMasters.Validators[0].(func(string) error)
	// zoneDescDnssecEnabled is the schema descriptor for dnssec_enabled field.
	zoneDescDnssecEnabled := zoneFields[5].Descriptor()
	// zone.DefaultDnssecEnabled holds the default value on creation for the dnssec_enabled field.
	zone.DefaultDnssecEnabled = zoneDescDnssecEnabled.Default.(bool)
	// zoneDescDescription is the schema descriptor for description field.
	zoneDescDescription := zoneFields[6].Descriptor()
	// zone.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	zone.DescriptionValidator = zoneDescDescription.Validators[0].(func(string) error)
	// zoneDescTemplateID is the schema descriptor for template_id field.
	zoneDescTemplateID := zoneFields[7].Descriptor()
	// zone.TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	zone.TemplateIDValidator = zoneDescTemplateID.Validators[0].(func(string) error)
	// zoneDescID is the schema descriptor for id field.
	zoneDescID := zoneFields[0].Descriptor()
	// zone.IDValidator is a validator for the "id" field. It is called by the builders before save.
	zone.IDValidator = zoneDescID.Validators[0].(func(string) error)
	zonetemplateMixin := schema.ZoneTemplate{}.Mixin()
	zonetemplate.Policy = privacy.NewPolicies(zonetemplateMixin[2], schema.ZoneTemplate{})
	zonetemplate.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := zonetemplate.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	zonetemplateMixinFields2 := zonetemplateMixin[2].Fields()
	_ = zonetemplateMixinFields2
	zonetemplateFields := schema.ZoneTemplate{}.Fields()
	_ = zonetemplateFields
	// zonetemplateDescTenantID is the schema descriptor for tenant_id field.
	zonetemplateDescTenantID := zonetemplateMixinFields2[0].Descriptor()
	// zonetemplate.DefaultTenantID holds the default value on creation for the tenant_id field.
	zonetemplate.DefaultTenantID = zonetemplateDescTenantID.Default.(uint32)
	// zonetemplateDescName is the schema descriptor for name field.
	zonetemplateDescName := zonetemplateFields[1].Descriptor()
	// zonetemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	zonetemplate.NameValidator = func() func(string) error {
		validators := zonetemplateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// zonetemplateDescDescription is the schema descriptor for description field.
	zonetemplateDescDescription := zonetemplateFields[2].Descriptor()
	// zonetemplate.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	zonetemplate.DescriptionValidator = zonetemplateDescDescription.Validators[0].(func(string) error)
	// zonetemplateDescID is the schema descriptor for id field.
	zonetemplateDescID := zonetemplateFields[0].Descriptor()
	// zonetemplate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	zonetemplate.IDValidator = zonetemplateDescID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
