// Code generated by ent, DO NOT EDIT.

package supermaster

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldTenantID, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldIP, v))
}

// Nameserver applies equality check predicate on the "nameserver" field. It's identical to NameserverEQ.
func Nameserver(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldNameserver, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldAccount, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotNull(FieldTenantID))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContainsFold(FieldIP, v))
}

// NameserverEQ applies the EQ predicate on the "nameserver" field.
func NameserverEQ(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldNameserver, v))
}

// NameserverNEQ applies the NEQ predicate on the "nameserver" field.
func NameserverNEQ(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldNameserver, v))
}

// NameserverIn applies the In predicate on the "nameserver" field.
func NameserverIn(vs ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldNameserver, vs...))
}

// NameserverNotIn applies the NotIn predicate on the "nameserver" field.
func NameserverNotIn(vs ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldNameserver, vs...))
}

// NameserverGT applies the GT predicate on the "nameserver" field.
func NameserverGT(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldNameserver, v))
}

// NameserverGTE applies the GTE predicate on the "nameserver" field.
func NameserverGTE(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldNameserver, v))
}

// NameserverLT applies the LT predicate on the "nameserver" field.
func NameserverLT(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldNameserver, v))
}

// NameserverLTE applies the LTE predicate on the "nameserver" field.
func NameserverLTE(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldNameserver, v))
}

// NameserverContains applies the Contains predicate on the "nameserver" field.
func NameserverContains(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContains(FieldNameserver, v))
}

// NameserverHasPrefix applies the HasPrefix predicate on the "nameserver" field.
func NameserverHasPrefix(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldHasPrefix(FieldNameserver, v))
}

// NameserverHasSuffix applies the HasSuffix predicate on the "nameserver" field.
func NameserverHasSuffix(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldHasSuffix(FieldNameserver, v))
}

// NameserverEqualFold applies the EqualFold predicate on the "nameserver" field.
func NameserverEqualFold(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEqualFold(FieldNameserver, v))
}

// NameserverContainsFold applies the ContainsFold predicate on the "nameserver" field.
func NameserverContainsFold(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContainsFold(FieldNameserver, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountIsNil applies the IsNil predicate on the "account" field.
func AccountIsNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldIsNull(FieldAccount))
}

// AccountNotNil applies the NotNil predicate on the "account" field.
func AccountNotNil() predicate.Supermaster {
	return predicate.Supermaster(sql.FieldNotNull(FieldAccount))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.Supermaster {
	return predicate.Supermaster(sql.FieldContainsFold(FieldAccount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Supermaster) predicate.Supermaster {
	return predicate.Supermaster(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Supermaster) predicate.Supermaster {
	return predicate.Supermaster(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Supermaster) predicate.Supermaster {
	return predicate.Supermaster(sql.NotPredicates(p))
}
