// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/go-tangra/go-tangra-dns/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/dnsconfig"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/supermaster"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zone"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zonetemplate"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DnsConfig is the client for interacting with the DnsConfig builders.
	DnsConfig *DnsConfigClient
	// Supermaster is the client for interacting with the Supermaster builders.
	Supermaster *SupermasterClient
	// Zone is the client for interacting with the Zone builders.
	Zone *ZoneClient
	// ZoneTemplate is the client for interacting with the ZoneTemplate builders.
	ZoneTemplate *ZoneTemplateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DnsConfig = NewDnsConfigClient(c.config)
	c.Supermaster = NewSupermasterClient(c.config)
	c.Zone = NewZoneClient(c.config)
	c.ZoneTemplate = NewZoneTemplateClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		DnsConfig:    NewDnsConfigClient(cfg),
		Supermaster:  NewSupermasterClient(cfg),
		Zone:         NewZoneClient(cfg),
		ZoneTemplate: NewZoneTemplateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		DnsConfig:    NewDnsConfigClient(cfg),
		Supermaster:  NewSupermasterClient(cfg),
		Zone:         NewZoneClient(cfg),
		ZoneTemplate: NewZoneTemplateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DnsConfig.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DnsConfig.Use(hooks...)
	c.Supermaster.Use(hooks...)
	c.Zone.Use(hooks...)
	c.ZoneTemplate.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DnsConfig.Intercept(interceptors...)
	c.Supermaster.Intercept(interceptors...)
	c.Zone.Intercept(interceptors...)
	c.ZoneTemplate.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DnsConfigMutation:
		return c.DnsConfig.mutate(ctx, m)
	case *SupermasterMutation:
		return c.Supermaster.mutate(ctx, m)
	case *ZoneMutation:
		return c.Zone.mutate(ctx, m)
	case *ZoneTemplateMutation:
		return c.ZoneTemplate.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DnsConfigClient is a client for the DnsConfig schema.
type DnsConfigClient struct {
	config
}

// NewDnsConfigClient returns a client for the DnsConfig from the given config.
func NewDnsConfigClient(c config) *DnsConfigClient {
	return &DnsConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dnsconfig.Hooks(f(g(h())))`.
func (c *DnsConfigClient) Use(hooks ...Hook) {
	c.hooks.DnsConfig = append(c.hooks.DnsConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dnsconfig.Intercept(f(g(h())))`.
func (c *DnsConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.DnsConfig = append(c.inters.DnsConfig, interceptors...)
}

// Create returns a builder for creating a DnsConfig entity.
func (c *DnsConfigClient) Create() *DnsConfigCreate {
	mutation := newDnsConfigMutation(c.config, OpCreate)
	return &DnsConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DnsConfig entities.
func (c *DnsConfigClient) CreateBulk(builders ...*DnsConfigCreate) *DnsConfigCreateBulk {
	return &DnsConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DnsConfigClient) MapCreateBulk(slice any, setFunc func(*DnsConfigCreate, int)) *DnsConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DnsConfigCreateBulk{err: fmt.Errorf("calling to DnsConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DnsConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DnsConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DnsConfig.
func (c *DnsConfigClient) Update() *DnsConfigUpdate {
	mutation := newDnsConfigMutation(c.config, OpUpdate)
	return &DnsConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DnsConfigClient) UpdateOne(_m *DnsConfig) *DnsConfigUpdateOne {
	mutation := newDnsConfigMutation(c.config, OpUpdateOne, withDnsConfig(_m))
	return &DnsConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DnsConfigClient) UpdateOneID(id string) *DnsConfigUpdateOne {
	mutation := newDnsConfigMutation(c.config, OpUpdateOne, withDnsConfigID(id))
	return &DnsConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DnsConfig.
func (c *DnsConfigClient) Delete() *DnsConfigDelete {
	mutation := newDnsConfigMutation(c.config, OpDelete)
	return &DnsConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DnsConfigClient) DeleteOne(_m *DnsConfig) *DnsConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DnsConfigClient) DeleteOneID(id string) *DnsConfigDeleteOne {
	builder := c.Delete().Where(dnsconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DnsConfigDeleteOne{builder}
}

// Query returns a query builder for DnsConfig.
func (c *DnsConfigClient) Query() *DnsConfigQuery {
	return &DnsConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDnsConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a DnsConfig entity by its id.
func (c *DnsConfigClient) Get(ctx context.Context, id string) (*DnsConfig, error) {
	return c.Query().Where(dnsconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DnsConfigClient) GetX(ctx context.Context, id string) *DnsConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DnsConfigClient) Hooks() []Hook {
	return c.hooks.DnsConfig
}

// Interceptors returns the client interceptors.
func (c *DnsConfigClient) Interceptors() []Interceptor {
	return c.inters.DnsConfig
}

func (c *DnsConfigClient) mutate(ctx context.Context, m *DnsConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DnsConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DnsConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DnsConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DnsConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DnsConfig mutation op: %q", m.Op())
	}
}

// SupermasterClient is a client for the Supermaster schema.
type SupermasterClient struct {
	config
}

// NewSupermasterClient returns a client for the Supermaster from the given config.
func NewSupermasterClient(c config) *SupermasterClient {
	return &SupermasterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `supermaster.Hooks(f(g(h())))`.
func (c *SupermasterClient) Use(hooks ...Hook) {
	c.hooks.Supermaster = append(c.hooks.Supermaster, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `supermaster.Intercept(f(g(h())))`.
func (c *SupermasterClient) Intercept(interceptors ...Interceptor) {
	c.inters.Supermaster = append(c.inters.Supermaster, interceptors...)
}

// Create returns a builder for creating a Supermaster entity.
func (c *SupermasterClient) Create() *SupermasterCreate {
	mutation := newSupermasterMutation(c.config, OpCreate)
	return &SupermasterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Supermaster entities.
func (c *SupermasterClient) CreateBulk(builders ...*SupermasterCreate) *SupermasterCreateBulk {
	return &SupermasterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SupermasterClient) MapCreateBulk(slice any, setFunc func(*SupermasterCreate, int)) *SupermasterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SupermasterCreateBulk{err: fmt.Errorf("calling to SupermasterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SupermasterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SupermasterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Supermaster.
func (c *SupermasterClient) Update() *SupermasterUpdate {
	mutation := newSupermasterMutation(c.config, OpUpdate)
	return &SupermasterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SupermasterClient) UpdateOne(_m *Supermaster) *SupermasterUpdateOne {
	mutation := newSupermasterMutation(c.config, OpUpdateOne, withSupermaster(_m))
	return &SupermasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SupermasterClient) UpdateOneID(id string) *SupermasterUpdateOne {
	mutation := newSupermasterMutation(c.config, OpUpdateOne, withSupermasterID(id))
	return &SupermasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Supermaster.
func (c *SupermasterClient) Delete() *SupermasterDelete {
	mutation := newSupermasterMutation(c.config, OpDelete)
	return &SupermasterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SupermasterClient) DeleteOne(_m *Supermaster) *SupermasterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SupermasterClient) DeleteOneID(id string) *SupermasterDeleteOne {
	builder := c.Delete().Where(supermaster.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SupermasterDeleteOne{builder}
}

// Query returns a query builder for Supermaster.
func (c *SupermasterClient) Query() *SupermasterQuery {
	return &SupermasterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSupermaster},
		inters: c.Interceptors(),
	}
}

// Get returns a Supermaster entity by its id.
func (c *SupermasterClient) Get(ctx context.Context, id string) (*Supermaster, error) {
	return c.Query().Where(supermaster.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SupermasterClient) GetX(ctx context.Context, id string) *Supermaster {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SupermasterClient) Hooks() []Hook {
	hooks := c.hooks.Supermaster
	return append(hooks[:len(hooks):len(hooks)], supermaster.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *SupermasterClient) Interceptors() []Interceptor {
	return c.inters.Supermaster
}

func (c *SupermasterClient) mutate(ctx context.Context, m *SupermasterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SupermasterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SupermasterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SupermasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SupermasterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Supermaster mutation op: %q", m.Op())
	}
}

// ZoneClient is a client for the Zone schema.
type ZoneClient struct {
	config
}

// NewZoneClient returns a client for the Zone from the given config.
func NewZoneClient(c config) *ZoneClient {
	return &ZoneClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `zone.Hooks(f(g(h())))`.
func (c *ZoneClient) Use(hooks ...Hook) {
	c.hooks.Zone = append(c.hooks.Zone, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `zone.Intercept(f(g(h())))`.
func (c *ZoneClient) Intercept(interceptors ...Interceptor) {
	c.inters.Zone = append(c.inters.Zone, interceptors...)
}

// Create returns a builder for creating a Zone entity.
func (c *ZoneClient) Create() *ZoneCreate {
	mutation := newZoneMutation(c.config, OpCreate)
	return &ZoneCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Zone entities.
func (c *ZoneClient) CreateBulk(builders ...*ZoneCreate) *ZoneCreateBulk {
	return &ZoneCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ZoneClient) MapCreateBulk(slice any, setFunc func(*ZoneCreate, int)) *ZoneCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ZoneCreateBulk{err: fmt.Errorf("calling to ZoneClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ZoneCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ZoneCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Zone.
func (c *ZoneClient) Update() *ZoneUpdate {
	mutation := newZoneMutation(c.config, OpUpdate)
	return &ZoneUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ZoneClient) UpdateOne(_m *Zone) *ZoneUpdateOne {
	mutation := newZoneMutation(c.config, OpUpdateOne, withZone(_m))
	return &ZoneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ZoneClient) UpdateOneID(id string) *ZoneUpdateOne {
	mutation := newZoneMutation(c.config, OpUpdateOne, withZoneID(id))
	return &ZoneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Zone.
func (c *ZoneClient) Delete() *ZoneDelete {
	mutation := newZoneMutation(c.config, OpDelete)
	return &ZoneDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ZoneClient) DeleteOne(_m *Zone) *ZoneDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ZoneClient) DeleteOneID(id string) *ZoneDeleteOne {
	builder := c.Delete().Where(zone.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ZoneDeleteOne{builder}
}

// Query returns a query builder for Zone.
func (c *ZoneClient) Query() *ZoneQuery {
	return &ZoneQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeZone},
		inters: c.Interceptors(),
	}
}

// Get returns a Zone entity by its id.
func (c *ZoneClient) Get(ctx context.Context, id string) (*Zone, error) {
	return c.Query().Where(zone.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ZoneClient) GetX(ctx context.Context, id string) *Zone {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ZoneClient) Hooks() []Hook {
	hooks := c.hooks.Zone
	return append(hooks[:len(hooks):len(hooks)], zone.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ZoneClient) Interceptors() []Interceptor {
	return c.inters.Zone
}

func (c *ZoneClient) mutate(ctx context.Context, m *ZoneMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ZoneCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ZoneUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ZoneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ZoneDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Zone mutation op: %q", m.Op())
	}
}

// ZoneTemplateClient is a client for the ZoneTemplate schema.
type ZoneTemplateClient struct {
	config
}

// NewZoneTemplateClient returns a client for the ZoneTemplate from the given config.
func NewZoneTemplateClient(c config) *ZoneTemplateClient {
	return &ZoneTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `zonetemplate.Hooks(f(g(h())))`.
func (c *ZoneTemplateClient) Use(hooks ...Hook) {
	c.hooks.ZoneTemplate = append(c.hooks.ZoneTemplate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `zonetemplate.Intercept(f(g(h())))`.
func (c *ZoneTemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.ZoneTemplate = append(c.inters.ZoneTemplate, interceptors...)
}

// Create returns a builder for creating a ZoneTemplate entity.
func (c *ZoneTemplateClient) Create() *ZoneTemplateCreate {
	mutation := newZoneTemplateMutation(c.config, OpCreate)
	return &ZoneTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ZoneTemplate entities.
func (c *ZoneTemplateClient) CreateBulk(builders ...*ZoneTemplateCreate) *ZoneTemplateCreateBulk {
	return &ZoneTemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ZoneTemplateClient) MapCreateBulk(slice any, setFunc func(*ZoneTemplateCreate, int)) *ZoneTemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ZoneTemplateCreateBulk{err: fmt.Errorf("calling to ZoneTemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ZoneTemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ZoneTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ZoneTemplate.
func (c *ZoneTemplateClient) Update() *ZoneTemplateUpdate {
	mutation := newZoneTemplateMutation(c.config, OpUpdate)
	return &ZoneTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ZoneTemplateClient) UpdateOne(_m *ZoneTemplate) *ZoneTemplateUpdateOne {
	mutation := newZoneTemplateMutation(c.config, OpUpdateOne, withZoneTemplate(_m))
	return &ZoneTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ZoneTemplateClient) UpdateOneID(id string) *ZoneTemplateUpdateOne {
	mutation := newZoneTemplateMutation(c.config, OpUpdateOne, withZoneTemplateID(id))
	return &ZoneTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ZoneTemplate.
func (c *ZoneTemplateClient) Delete() *ZoneTemplateDelete {
	mutation := newZoneTemplateMutation(c.config, OpDelete)
	return &ZoneTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ZoneTemplateClient) DeleteOne(_m *ZoneTemplate) *ZoneTemplateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ZoneTemplateClient) DeleteOneID(id string) *ZoneTemplateDeleteOne {
	builder := c.Delete().Where(zonetemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ZoneTemplateDeleteOne{builder}
}

// Query returns a query builder for ZoneTemplate.
func (c *ZoneTemplateClient) Query() *ZoneTemplateQuery {
	return &ZoneTemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeZoneTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a ZoneTemplate entity by its id.
func (c *ZoneTemplateClient) Get(ctx context.Context, id string) (*ZoneTemplate, error) {
	return c.Query().Where(zonetemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ZoneTemplateClient) GetX(ctx context.Context, id string) *ZoneTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ZoneTemplateClient) Hooks() []Hook {
	hooks := c.hooks.ZoneTemplate
	return append(hooks[:len(hooks):len(hooks)], zonetemplate.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ZoneTemplateClient) Interceptors() []Interceptor {
	return c.inters.ZoneTemplate
}

func (c *ZoneTemplateClient) mutate(ctx context.Context, m *ZoneTemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ZoneTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ZoneTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ZoneTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ZoneTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ZoneTemplate mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DnsConfig, Supermaster, Zone, ZoneTemplate []ent.Hook
	}
	inters struct {
		DnsConfig, Supermaster, Zone, ZoneTemplate []ent.Interceptor
	}
)
