// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/dnsconfig"
)

// DnsConfigCreate is the builder for creating a DnsConfig entity.
type DnsConfigCreate struct {
	config
	mutation *DnsConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *DnsConfigCreate) SetCreateTime(v time.Time) *DnsConfigCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *DnsConfigCreate) SetNillableCreateTime(v *time.Time) *DnsConfigCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *DnsConfigCreate) SetUpdateTime(v time.Time) *DnsConfigCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *DnsConfigCreate) SetNillableUpdateTime(v *time.Time) *DnsConfigCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *DnsConfigCreate) SetDeleteTime(v time.Time) *DnsConfigCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *DnsConfigCreate) SetNillableDeleteTime(v *time.Time) *DnsConfigCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetData sets the "data" field.
func (_c *DnsConfigCreate) SetData(v string) *DnsConfigCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_c *DnsConfigCreate) SetNillableData(v *string) *DnsConfigCreate {
	if v != nil {
		_c.SetData(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DnsConfigCreate) SetID(v string) *DnsConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DnsConfigMutation object of the builder.
func (_c *DnsConfigCreate) Mutation() *DnsConfigMutation {
	return _c.mutation
}

// Save creates the DnsConfig in the database.
func (_c *DnsConfigCreate) Save(ctx context.Context) (*DnsConfig, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DnsConfigCreate) SaveX(ctx context.Context) *DnsConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DnsConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DnsConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DnsConfigCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := dnsconfig.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DnsConfig.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DnsConfigCreate) sqlSave(ctx context.Context) (*DnsConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DnsConfig.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DnsConfigCreate) createSpec() (*DnsConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &DnsConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dnsconfig.Table, sqlgraph.NewFieldSpec(dnsconfig.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(dnsconfig.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(dnsconfig.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(dnsconfig.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(dnsconfig.FieldData, field.TypeString, value)
		_node.Data = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DnsConfig.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DnsConfigUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DnsConfigCreate) OnConflict(opts ...sql.ConflictOption) *DnsConfigUpsertOne {
	_c.conflict = opts
	return &DnsConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DnsConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DnsConfigCreate) OnConflictColumns(columns ...string) *DnsConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DnsConfigUpsertOne{
		create: _c,
	}
}

type (
	// DnsConfigUpsertOne is the builder for "upsert"-ing
	//  one DnsConfig node.
	DnsConfigUpsertOne struct {
		create *DnsConfigCreate
	}

	// DnsConfigUpsert is the "OnConflict" setter.
	DnsConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *DnsConfigUpsert) SetUpdateTime(v time.Time) *DnsConfigUpsert {
	u.Set(dnsconfig.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DnsConfigUpsert) UpdateUpdateTime() *DnsConfigUpsert {
	u.SetExcluded(dnsconfig.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DnsConfigUpsert) ClearUpdateTime() *DnsConfigUpsert {
	u.SetNull(dnsconfig.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *DnsConfigUpsert) SetDeleteTime(v time.Time) *DnsConfigUpsert {
	u.Set(dnsconfig.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DnsConfigUpsert) UpdateDeleteTime() *DnsConfigUpsert {
	u.SetExcluded(dnsconfig.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DnsConfigUpsert) ClearDeleteTime() *DnsConfigUpsert {
	u.SetNull(dnsconfig.FieldDeleteTime)
	return u
}

// SetData sets the "data" field.
func (u *DnsConfigUpsert) SetData(v string) *DnsConfigUpsert {
	u.Set(dnsconfig.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *DnsConfigUpsert) UpdateData() *DnsConfigUpsert {
	u.SetExcluded(dnsconfig.FieldData)
	return u
}

// ClearData clears the value of the "data" field.
func (u *DnsConfigUpsert) ClearData() *DnsConfigUpsert {
	u.SetNull(dnsconfig.FieldData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DnsConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dnsconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DnsConfigUpsertOne) UpdateNewValues() *DnsConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dnsconfig.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(dnsconfig.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DnsConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DnsConfigUpsertOne) Ignore() *DnsConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DnsConfigUpsertOne) DoNothing() *DnsConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DnsConfigCreate.OnConflict
// documentation for more info.
func (u *DnsConfigUpsertOne) Update(set func(*DnsConfigUpsert)) *DnsConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DnsConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DnsConfigUpsertOne) SetUpdateTime(v time.Time) *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DnsConfigUpsertOne) UpdateUpdateTime() *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DnsConfigUpsertOne) ClearUpdateTime() *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *DnsConfigUpsertOne) SetDeleteTime(v time.Time) *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DnsConfigUpsertOne) UpdateDeleteTime() *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DnsConfigUpsertOne) ClearDeleteTime() *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.ClearDeleteTime()
	})
}

// SetData sets the "data" field.
func (u *DnsConfigUpsertOne) SetData(v string) *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *DnsConfigUpsertOne) UpdateData() *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *DnsConfigUpsertOne) ClearData() *DnsConfigUpsertOne {
	return u.Update(func(s *DnsConfigUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *DnsConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DnsConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DnsConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DnsConfigUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DnsConfigUpsertOne.ID is not supported by MySQL driver. Use DnsConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DnsConfigUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DnsConfigCreateBulk is the builder for creating many DnsConfig entities in bulk.
type DnsConfigCreateBulk struct {
	config
	err      error
	builders []*DnsConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the DnsConfig entities in the database.
func (_c *DnsConfigCreateBulk) Save(ctx context.Context) ([]*DnsConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DnsConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DnsConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DnsConfigCreateBulk) SaveX(ctx context.Context) []*DnsConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DnsConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DnsConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DnsConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DnsConfigUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DnsConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *DnsConfigUpsertBulk {
	_c.conflict = opts
	return &DnsConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DnsConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DnsConfigCreateBulk) OnConflictColumns(columns ...string) *DnsConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DnsConfigUpsertBulk{
		create: _c,
	}
}

// DnsConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of DnsConfig nodes.
type DnsConfigUpsertBulk struct {
	create *DnsConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DnsConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dnsconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DnsConfigUpsertBulk) UpdateNewValues() *DnsConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dnsconfig.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(dnsconfig.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DnsConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DnsConfigUpsertBulk) Ignore() *DnsConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DnsConfigUpsertBulk) DoNothing() *DnsConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DnsConfigCreateBulk.OnConflict
// documentation for more info.
func (u *DnsConfigUpsertBulk) Update(set func(*DnsConfigUpsert)) *DnsConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DnsConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DnsConfigUpsertBulk) SetUpdateTime(v time.Time) *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DnsConfigUpsertBulk) UpdateUpdateTime() *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DnsConfigUpsertBulk) ClearUpdateTime() *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *DnsConfigUpsertBulk) SetDeleteTime(v time.Time) *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DnsConfigUpsertBulk) UpdateDeleteTime() *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DnsConfigUpsertBulk) ClearDeleteTime() *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.ClearDeleteTime()
	})
}

// SetData sets the "data" field.
func (u *DnsConfigUpsertBulk) SetData(v string) *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *DnsConfigUpsertBulk) UpdateData() *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *DnsConfigUpsertBulk) ClearData() *DnsConfigUpsertBulk {
	return u.Update(func(s *DnsConfigUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *DnsConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DnsConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DnsConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DnsConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
