// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/dnsconfig"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
)

// DnsConfigUpdate is the builder for updating DnsConfig entities.
type DnsConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *DnsConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DnsConfigUpdate builder.
func (_u *DnsConfigUpdate) Where(ps ...predicate.DnsConfig) *DnsConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DnsConfigUpdate) SetUpdateTime(v time.Time) *DnsConfigUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableUpdateTime(v *time.Time) *DnsConfigUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DnsConfigUpdate) ClearUpdateTime() *DnsConfigUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DnsConfigUpdate) SetDeleteTime(v time.Time) *DnsConfigUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableDeleteTime(v *time.Time) *DnsConfigUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DnsConfigUpdate) ClearDeleteTime() *DnsConfigUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetData sets the "data" field.
func (_u *DnsConfigUpdate) SetData(v string) *DnsConfigUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableData(v *string) *DnsConfigUpdate {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *DnsConfigUpdate) ClearData() *DnsConfigUpdate {
	_u.mutation.ClearData()
	return _u
}

// Mutation returns the DnsConfigMutation object of the builder.
func (_u *DnsConfigUpdate) Mutation() *DnsConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DnsConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DnsConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DnsConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DnsConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DnsConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DnsConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DnsConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dnsconfig.Table, dnsconfig.Columns, sqlgraph.NewFieldSpec(dnsconfig.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(dnsconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(dnsconfig.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(dnsconfig.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(dnsconfig.FieldData, field.TypeString, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(dnsconfig.FieldData, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DnsConfigUpdateOne is the builder for updating a single DnsConfig entity.
type DnsConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DnsConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *DnsConfigUpdateOne) SetUpdateTime(v time.Time) *DnsConfigUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableUpdateTime(v *time.Time) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DnsConfigUpdateOne) ClearUpdateTime() *DnsConfigUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DnsConfigUpdateOne) SetDeleteTime(v time.Time) *DnsConfigUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableDeleteTime(v *time.Time) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DnsConfigUpdateOne) ClearDeleteTime() *DnsConfigUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetData sets the "data" field.
func (_u *DnsConfigUpdateOne) SetData(v string) *DnsConfigUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableData(v *string) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *DnsConfigUpdateOne) ClearData() *DnsConfigUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// Mutation returns the DnsConfigMutation object of the builder.
func (_u *DnsConfigUpdateOne) Mutation() *DnsConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the DnsConfigUpdate builder.
func (_u *DnsConfigUpdateOne) Where(ps ...predicate.DnsConfig) *DnsConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DnsConfigUpdateOne) Select(field string, fields ...string) *DnsConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DnsConfig entity.
func (_u *DnsConfigUpdateOne) Save(ctx context.Context) (*DnsConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DnsConfigUpdateOne) SaveX(ctx context.Context) *DnsConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DnsConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DnsConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DnsConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DnsConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DnsConfigUpdateOne) sqlSave(ctx context.Context) (_node *DnsConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(dnsconfig.Table, dnsconfig.Columns, sqlgraph.NewFieldSpec(dnsconfig.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DnsConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnsconfig.FieldID)
		for _, f := range fields {
			if !dnsconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dnsconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(dnsconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(dnsconfig.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(dnsconfig.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(dnsconfig.FieldData, field.TypeString, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(dnsconfig.FieldData, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DnsConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
