// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/supermaster"
)

// SupermasterUpdate is the builder for updating Supermaster entities.
type SupermasterUpdate struct {
	config
	hooks     []Hook
	mutation  *SupermasterMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SupermasterUpdate builder.
func (_u *SupermasterUpdate) Where(ps ...predicate.Supermaster) *SupermasterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SupermasterUpdate) SetCreateBy(v uint32) *SupermasterUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SupermasterUpdate) SetNillableCreateBy(v *uint32) *SupermasterUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SupermasterUpdate) AddCreateBy(v int32) *SupermasterUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SupermasterUpdate) ClearCreateBy() *SupermasterUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SupermasterUpdate) SetUpdateTime(v time.Time) *SupermasterUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SupermasterUpdate) SetNillableUpdateTime(v *time.Time) *SupermasterUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SupermasterUpdate) ClearUpdateTime() *SupermasterUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SupermasterUpdate) SetDeleteTime(v time.Time) *SupermasterUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SupermasterUpdate) SetNillableDeleteTime(v *time.Time) *SupermasterUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SupermasterUpdate) ClearDeleteTime() *SupermasterUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetIP sets the "ip" field.
func (_u *SupermasterUpdate) SetIP(v string) *SupermasterUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SupermasterUpdate) SetNillableIP(v *string) *SupermasterUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetNameserver sets the "nameserver" field.
func (_u *SupermasterUpdate) SetNameserver(v string) *SupermasterUpdate {
	_u.mutation.SetNameserver(v)
	return _u
}

// SetNillableNameserver sets the "nameserver" field if the given value is not nil.
func (_u *SupermasterUpdate) SetNillableNameserver(v *string) *SupermasterUpdate {
	if v != nil {
		_u.SetNameserver(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *SupermasterUpdate) SetAccount(v string) *SupermasterUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *SupermasterUpdate) SetNillableAccount(v *string) *SupermasterUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// ClearAccount clears the value of the "account" field.
func (_u *SupermasterUpdate) ClearAccount() *SupermasterUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Mutation returns the SupermasterMutation object of the builder.
func (_u *SupermasterUpdate) Mutation() *SupermasterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupermasterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupermasterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupermasterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupermasterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupermasterUpdate) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := supermaster.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Supermaster.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nameserver(); ok {
		if err := supermaster.NameserverValidator(v); err != nil {
			return &ValidationError{Name: "nameserver", err: fmt.Errorf(`ent: validator failed for field "Supermaster.nameserver": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Account(); ok {
		if err := supermaster.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Supermaster.account": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SupermasterUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SupermasterUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SupermasterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supermaster.Table, supermaster.Columns, sqlgraph.NewFieldSpec(supermaster.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(supermaster.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(supermaster.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(supermaster.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(supermaster.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(supermaster.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(supermaster.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(supermaster.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(supermaster.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(supermaster.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(supermaster.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nameserver(); ok {
		_spec.SetField(supermaster.FieldNameserver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(supermaster.FieldAccount, field.TypeString, value)
	}
	if _u.mutation.AccountCleared() {
		_spec.ClearField(supermaster.FieldAccount, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supermaster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupermasterUpdateOne is the builder for updating a single Supermaster entity.
type SupermasterUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SupermasterMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *SupermasterUpdateOne) SetCreateBy(v uint32) *SupermasterUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SupermasterUpdateOne) SetNillableCreateBy(v *uint32) *SupermasterUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SupermasterUpdateOne) AddCreateBy(v int32) *SupermasterUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SupermasterUpdateOne) ClearCreateBy() *SupermasterUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SupermasterUpdateOne) SetUpdateTime(v time.Time) *SupermasterUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SupermasterUpdateOne) SetNillableUpdateTime(v *time.Time) *SupermasterUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SupermasterUpdateOne) ClearUpdateTime() *SupermasterUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SupermasterUpdateOne) SetDeleteTime(v time.Time) *SupermasterUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SupermasterUpdateOne) SetNillableDeleteTime(v *time.Time) *SupermasterUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SupermasterUpdateOne) ClearDeleteTime() *SupermasterUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetIP sets the "ip" field.
func (_u *SupermasterUpdateOne) SetIP(v string) *SupermasterUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SupermasterUpdateOne) SetNillableIP(v *string) *SupermasterUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetNameserver sets the "nameserver" field.
func (_u *SupermasterUpdateOne) SetNameserver(v string) *SupermasterUpdateOne {
	_u.mutation.SetNameserver(v)
	return _u
}

// SetNillableNameserver sets the "nameserver" field if the given value is not nil.
func (_u *SupermasterUpdateOne) SetNillableNameserver(v *string) *SupermasterUpdateOne {
	if v != nil {
		_u.SetNameserver(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *SupermasterUpdateOne) SetAccount(v string) *SupermasterUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *SupermasterUpdateOne) SetNillableAccount(v *string) *SupermasterUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// ClearAccount clears the value of the "account" field.
func (_u *SupermasterUpdateOne) ClearAccount() *SupermasterUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Mutation returns the SupermasterMutation object of the builder.
func (_u *SupermasterUpdateOne) Mutation() *SupermasterMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupermasterUpdate builder.
func (_u *SupermasterUpdateOne) Where(ps ...predicate.Supermaster) *SupermasterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupermasterUpdateOne) Select(field string, fields ...string) *SupermasterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Supermaster entity.
func (_u *SupermasterUpdateOne) Save(ctx context.Context) (*Supermaster, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupermasterUpdateOne) SaveX(ctx context.Context) *Supermaster {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupermasterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupermasterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupermasterUpdateOne) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := supermaster.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Supermaster.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nameserver(); ok {
		if err := supermaster.NameserverValidator(v); err != nil {
			return &ValidationError{Name: "nameserver", err: fmt.Errorf(`ent: validator failed for field "Supermaster.nameserver": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Account(); ok {
		if err := supermaster.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Supermaster.account": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SupermasterUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SupermasterUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SupermasterUpdateOne) sqlSave(ctx context.Context) (_node *Supermaster, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supermaster.Table, supermaster.Columns, sqlgraph.NewFieldSpec(supermaster.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Supermaster.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supermaster.FieldID)
		for _, f := range fields {
			if !supermaster.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supermaster.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(supermaster.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(supermaster.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(supermaster.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(supermaster.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(supermaster.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(supermaster.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(supermaster.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(supermaster.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(supermaster.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(supermaster.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nameserver(); ok {
		_spec.SetField(supermaster.FieldNameserver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(supermaster.FieldAccount, field.TypeString, value)
	}
	if _u.mutation.AccountCleared() {
		_spec.ClearField(supermaster.FieldAccount, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Supermaster{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supermaster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
