// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/supermaster"
)

// SupermasterCreate is the builder for creating a Supermaster entity.
type SupermasterCreate struct {
	config
	mutation *SupermasterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SupermasterCreate) SetCreateBy(v uint32) *SupermasterCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SupermasterCreate) SetNillableCreateBy(v *uint32) *SupermasterCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SupermasterCreate) SetCreateTime(v time.Time) *SupermasterCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SupermasterCreate) SetNillableCreateTime(v *time.Time) *SupermasterCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SupermasterCreate) SetUpdateTime(v time.Time) *SupermasterCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SupermasterCreate) SetNillableUpdateTime(v *time.Time) *SupermasterCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SupermasterCreate) SetDeleteTime(v time.Time) *SupermasterCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SupermasterCreate) SetNillableDeleteTime(v *time.Time) *SupermasterCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SupermasterCreate) SetTenantID(v uint32) *SupermasterCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SupermasterCreate) SetNillableTenantID(v *uint32) *SupermasterCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *SupermasterCreate) SetIP(v string) *SupermasterCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNameserver sets the "nameserver" field.
func (_c *SupermasterCreate) SetNameserver(v string) *SupermasterCreate {
	_c.mutation.SetNameserver(v)
	return _c
}

// SetAccount sets the "account" field.
func (_c *SupermasterCreate) SetAccount(v string) *SupermasterCreate {
	_c.mutation.SetAccount(v)
	return _c
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_c *SupermasterCreate) SetNillableAccount(v *string) *SupermasterCreate {
	if v != nil {
		_c.SetAccount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SupermasterCreate) SetID(v string) *SupermasterCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SupermasterMutation object of the builder.
func (_c *SupermasterCreate) Mutation() *SupermasterMutation {
	return _c.mutation
}

// Save creates the Supermaster in the database.
func (_c *SupermasterCreate) Save(ctx context.Context) (*Supermaster, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupermasterCreate) SaveX(ctx context.Context) *Supermaster {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupermasterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupermasterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupermasterCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := supermaster.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupermasterCreate) check() error {
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Supermaster.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := supermaster.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Supermaster.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Nameserver(); !ok {
		return &ValidationError{Name: "nameserver", err: errors.New(`ent: missing required field "Supermaster.nameserver"`)}
	}
	if v, ok := _c.mutation.Nameserver(); ok {
		if err := supermaster.NameserverValidator(v); err != nil {
			return &ValidationError{Name: "nameserver", err: fmt.Errorf(`ent: validator failed for field "Supermaster.nameserver": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Account(); ok {
		if err := supermaster.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Supermaster.account": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := supermaster.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Supermaster.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SupermasterCreate) sqlSave(ctx context.Context) (*Supermaster, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Supermaster.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupermasterCreate) createSpec() (*Supermaster, *sqlgraph.CreateSpec) {
	var (
		_node = &Supermaster{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supermaster.Table, sqlgraph.NewFieldSpec(supermaster.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(supermaster.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(supermaster.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(supermaster.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(supermaster.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(supermaster.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(supermaster.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Nameserver(); ok {
		_spec.SetField(supermaster.FieldNameserver, field.TypeString, value)
		_node.Nameserver = value
	}
	if value, ok := _c.mutation.Account(); ok {
		_spec.SetField(supermaster.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Supermaster.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupermasterUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SupermasterCreate) OnConflict(opts ...sql.ConflictOption) *SupermasterUpsertOne {
	_c.conflict = opts
	return &SupermasterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Supermaster.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupermasterCreate) OnConflictColumns(columns ...string) *SupermasterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupermasterUpsertOne{
		create: _c,
	}
}

type (
	// SupermasterUpsertOne is the builder for "upsert"-ing
	//  one Supermaster node.
	SupermasterUpsertOne struct {
		create *SupermasterCreate
	}

	// SupermasterUpsert is the "OnConflict" setter.
	SupermasterUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SupermasterUpsert) SetCreateBy(v uint32) *SupermasterUpsert {
	u.Set(supermaster.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SupermasterUpsert) UpdateCreateBy() *SupermasterUpsert {
	u.SetExcluded(supermaster.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SupermasterUpsert) AddCreateBy(v uint32) *SupermasterUpsert {
	u.Add(supermaster.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SupermasterUpsert) ClearCreateBy() *SupermasterUpsert {
	u.SetNull(supermaster.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SupermasterUpsert) SetUpdateTime(v time.Time) *SupermasterUpsert {
	u.Set(supermaster.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SupermasterUpsert) UpdateUpdateTime() *SupermasterUpsert {
	u.SetExcluded(supermaster.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SupermasterUpsert) ClearUpdateTime() *SupermasterUpsert {
	u.SetNull(supermaster.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SupermasterUpsert) SetDeleteTime(v time.Time) *SupermasterUpsert {
	u.Set(supermaster.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SupermasterUpsert) UpdateDeleteTime() *SupermasterUpsert {
	u.SetExcluded(supermaster.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SupermasterUpsert) ClearDeleteTime() *SupermasterUpsert {
	u.SetNull(supermaster.FieldDeleteTime)
	return u
}

// SetIP sets the "ip" field.
func (u *SupermasterUpsert) SetIP(v string) *SupermasterUpsert {
	u.Set(supermaster.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SupermasterUpsert) UpdateIP() *SupermasterUpsert {
	u.SetExcluded(supermaster.FieldIP)
	return u
}

// SetNameserver sets the "nameserver" field.
func (u *SupermasterUpsert) SetNameserver(v string) *SupermasterUpsert {
	u.Set(supermaster.FieldNameserver, v)
	return u
}

// UpdateNameserver sets the "nameserver" field to the value that was provided on create.
func (u *SupermasterUpsert) UpdateNameserver() *SupermasterUpsert {
	u.SetExcluded(supermaster.FieldNameserver)
	return u
}

// SetAccount sets the "account" field.
func (u *SupermasterUpsert) SetAccount(v string) *SupermasterUpsert {
	u.Set(supermaster.FieldAccount, v)
	return u
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *SupermasterUpsert) UpdateAccount() *SupermasterUpsert {
	u.SetExcluded(supermaster.FieldAccount)
	return u
}

// ClearAccount clears the value of the "account" field.
func (u *SupermasterUpsert) ClearAccount() *SupermasterUpsert {
	u.SetNull(supermaster.FieldAccount)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Supermaster.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(supermaster.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SupermasterUpsertOne) UpdateNewValues() *SupermasterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(supermaster.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(supermaster.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(supermaster.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Supermaster.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupermasterUpsertOne) Ignore() *SupermasterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupermasterUpsertOne) DoNothing() *SupermasterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupermasterCreate.OnConflict
// documentation for more info.
func (u *SupermasterUpsertOne) Update(set func(*SupermasterUpsert)) *SupermasterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupermasterUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SupermasterUpsertOne) SetCreateBy(v uint32) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SupermasterUpsertOne) AddCreateBy(v uint32) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SupermasterUpsertOne) UpdateCreateBy() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SupermasterUpsertOne) ClearCreateBy() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SupermasterUpsertOne) SetUpdateTime(v time.Time) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SupermasterUpsertOne) UpdateUpdateTime() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SupermasterUpsertOne) ClearUpdateTime() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SupermasterUpsertOne) SetDeleteTime(v time.Time) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SupermasterUpsertOne) UpdateDeleteTime() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SupermasterUpsertOne) ClearDeleteTime() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearDeleteTime()
	})
}

// SetIP sets the "ip" field.
func (u *SupermasterUpsertOne) SetIP(v string) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SupermasterUpsertOne) UpdateIP() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateIP()
	})
}

// SetNameserver sets the "nameserver" field.
func (u *SupermasterUpsertOne) SetNameserver(v string) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetNameserver(v)
	})
}

// UpdateNameserver sets the "nameserver" field to the value that was provided on create.
func (u *SupermasterUpsertOne) UpdateNameserver() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateNameserver()
	})
}

// SetAccount sets the "account" field.
func (u *SupermasterUpsertOne) SetAccount(v string) *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetAccount(v)
	})
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *SupermasterUpsertOne) UpdateAccount() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateAccount()
	})
}

// ClearAccount clears the value of the "account" field.
func (u *SupermasterUpsertOne) ClearAccount() *SupermasterUpsertOne {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearAccount()
	})
}

// Exec executes the query.
func (u *SupermasterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupermasterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupermasterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupermasterUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SupermasterUpsertOne.ID is not supported by MySQL driver. Use SupermasterUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupermasterUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupermasterCreateBulk is the builder for creating many Supermaster entities in bulk.
type SupermasterCreateBulk struct {
	config
	err      error
	builders []*SupermasterCreate
	conflict []sql.ConflictOption
}

// Save creates the Supermaster entities in the database.
func (_c *SupermasterCreateBulk) Save(ctx context.Context) ([]*Supermaster, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Supermaster, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupermasterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupermasterCreateBulk) SaveX(ctx context.Context) []*Supermaster {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupermasterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupermasterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Supermaster.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupermasterUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SupermasterCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupermasterUpsertBulk {
	_c.conflict = opts
	return &SupermasterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Supermaster.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupermasterCreateBulk) OnConflictColumns(columns ...string) *SupermasterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupermasterUpsertBulk{
		create: _c,
	}
}

// SupermasterUpsertBulk is the builder for "upsert"-ing
// a bulk of Supermaster nodes.
type SupermasterUpsertBulk struct {
	create *SupermasterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Supermaster.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(supermaster.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SupermasterUpsertBulk) UpdateNewValues() *SupermasterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(supermaster.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(supermaster.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(supermaster.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Supermaster.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupermasterUpsertBulk) Ignore() *SupermasterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupermasterUpsertBulk) DoNothing() *SupermasterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupermasterCreateBulk.OnConflict
// documentation for more info.
func (u *SupermasterUpsertBulk) Update(set func(*SupermasterUpsert)) *SupermasterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupermasterUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SupermasterUpsertBulk) SetCreateBy(v uint32) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SupermasterUpsertBulk) AddCreateBy(v uint32) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SupermasterUpsertBulk) UpdateCreateBy() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SupermasterUpsertBulk) ClearCreateBy() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SupermasterUpsertBulk) SetUpdateTime(v time.Time) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SupermasterUpsertBulk) UpdateUpdateTime() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SupermasterUpsertBulk) ClearUpdateTime() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SupermasterUpsertBulk) SetDeleteTime(v time.Time) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SupermasterUpsertBulk) UpdateDeleteTime() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SupermasterUpsertBulk) ClearDeleteTime() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearDeleteTime()
	})
}

// SetIP sets the "ip" field.
func (u *SupermasterUpsertBulk) SetIP(v string) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SupermasterUpsertBulk) UpdateIP() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateIP()
	})
}

// SetNameserver sets the "nameserver" field.
func (u *SupermasterUpsertBulk) SetNameserver(v string) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetNameserver(v)
	})
}

// UpdateNameserver sets the "nameserver" field to the value that was provided on create.
func (u *SupermasterUpsertBulk) UpdateNameserver() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateNameserver()
	})
}

// SetAccount sets the "account" field.
func (u *SupermasterUpsertBulk) SetAccount(v string) *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.SetAccount(v)
	})
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *SupermasterUpsertBulk) UpdateAccount() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.UpdateAccount()
	})
}

// ClearAccount clears the value of the "account" field.
func (u *SupermasterUpsertBulk) ClearAccount() *SupermasterUpsertBulk {
	return u.Update(func(s *SupermasterUpsert) {
		s.ClearAccount()
	})
}

// Exec executes the query.
func (u *SupermasterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupermasterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupermasterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupermasterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
