// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zone"
)

// ZoneUpdate is the builder for updating Zone entities.
type ZoneUpdate struct {
	config
	hooks     []Hook
	mutation  *ZoneMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ZoneUpdate builder.
func (_u *ZoneUpdate) Where(ps ...predicate.Zone) *ZoneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *ZoneUpdate) SetCreateBy(v uint32) *ZoneUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableCreateBy(v *uint32) *ZoneUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ZoneUpdate) AddCreateBy(v int32) *ZoneUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ZoneUpdate) ClearCreateBy() *ZoneUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ZoneUpdate) SetUpdateTime(v time.Time) *ZoneUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableUpdateTime(v *time.Time) *ZoneUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ZoneUpdate) ClearUpdateTime() *ZoneUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ZoneUpdate) SetDeleteTime(v time.Time) *ZoneUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableDeleteTime(v *time.Time) *ZoneUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ZoneUpdate) ClearDeleteTime() *ZoneUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetPdnsID sets the "pdns_id" field.
func (_u *ZoneUpdate) SetPdnsID(v string) *ZoneUpdate {
	_u.mutation.SetPdnsID(v)
	return _u
}

// SetNillablePdnsID sets the "pdns_id" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillablePdnsID(v *string) *ZoneUpdate {
	if v != nil {
		_u.SetPdnsID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ZoneUpdate) SetName(v string) *ZoneUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableName(v *string) *ZoneUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ZoneUpdate) SetKind(v zone.Kind) *ZoneUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableKind(v *zone.Kind) *ZoneUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetMasters sets the "masters" field.
func (_u *ZoneUpdate) SetMasters(v string) *ZoneUpdate {
	_u.mutation.SetMasters(v)
	return _u
}

// SetNillableMasters sets the "masters" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableMasters(v *string) *ZoneUpdate {
	if v != nil {
		_u.SetMasters(*v)
	}
	return _u
}

// ClearMasters clears the value of the "masters" field.
func (_u *ZoneUpdate) ClearMasters() *ZoneUpdate {
	_u.mutation.ClearMasters()
	return _u
}

// SetDnssecEnabled sets the "dnssec_enabled" field.
func (_u *ZoneUpdate) SetDnssecEnabled(v bool) *ZoneUpdate {
	_u.mutation.SetDnssecEnabled(v)
	return _u
}

// SetNillableDnssecEnabled sets the "dnssec_enabled" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableDnssecEnabled(v *bool) *ZoneUpdate {
	if v != nil {
		_u.SetDnssecEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ZoneUpdate) SetDescription(v string) *ZoneUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableDescription(v *string) *ZoneUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ZoneUpdate) ClearDescription() *ZoneUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *ZoneUpdate) SetTemplateID(v string) *ZoneUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *ZoneUpdate) SetNillableTemplateID(v *string) *ZoneUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// ClearTemplateID clears the value of the "template_id" field.
func (_u *ZoneUpdate) ClearTemplateID() *ZoneUpdate {
	_u.mutation.ClearTemplateID()
	return _u
}

// Mutation returns the ZoneMutation object of the builder.
func (_u *ZoneUpdate) Mutation() *ZoneMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ZoneUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZoneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ZoneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZoneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZoneUpdate) check() error {
	if v, ok := _u.mutation.PdnsID(); ok {
		if err := zone.PdnsIDValidator(v); err != nil {
			return &ValidationError{Name: "pdns_id", err: fmt.Errorf(`ent: validator failed for field "Zone.pdns_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := zone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Zone.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := zone.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Zone.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Masters(); ok {
		if err := zone.MastersValidator(v); err != nil {
			return &ValidationError{Name: "masters", err: fmt.Errorf(`ent: validator failed for field "Zone.masters": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := zone.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Zone.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := zone.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "Zone.template_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ZoneUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ZoneUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ZoneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zone.Table, zone.Columns, sqlgraph.NewFieldSpec(zone.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(zone.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(zone.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(zone.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(zone.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(zone.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(zone.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(zone.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(zone.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(zone.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PdnsID(); ok {
		_spec.SetField(zone.FieldPdnsID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(zone.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(zone.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Masters(); ok {
		_spec.SetField(zone.FieldMasters, field.TypeString, value)
	}
	if _u.mutation.MastersCleared() {
		_spec.ClearField(zone.FieldMasters, field.TypeString)
	}
	if value, ok := _u.mutation.DnssecEnabled(); ok {
		_spec.SetField(zone.FieldDnssecEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(zone.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(zone.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(zone.FieldTemplateID, field.TypeString, value)
	}
	if _u.mutation.TemplateIDCleared() {
		_spec.ClearField(zone.FieldTemplateID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ZoneUpdateOne is the builder for updating a single Zone entity.
type ZoneUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ZoneMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *ZoneUpdateOne) SetCreateBy(v uint32) *ZoneUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableCreateBy(v *uint32) *ZoneUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ZoneUpdateOne) AddCreateBy(v int32) *ZoneUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ZoneUpdateOne) ClearCreateBy() *ZoneUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ZoneUpdateOne) SetUpdateTime(v time.Time) *ZoneUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableUpdateTime(v *time.Time) *ZoneUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ZoneUpdateOne) ClearUpdateTime() *ZoneUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ZoneUpdateOne) SetDeleteTime(v time.Time) *ZoneUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableDeleteTime(v *time.Time) *ZoneUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ZoneUpdateOne) ClearDeleteTime() *ZoneUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetPdnsID sets the "pdns_id" field.
func (_u *ZoneUpdateOne) SetPdnsID(v string) *ZoneUpdateOne {
	_u.mutation.SetPdnsID(v)
	return _u
}

// SetNillablePdnsID sets the "pdns_id" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillablePdnsID(v *string) *ZoneUpdateOne {
	if v != nil {
		_u.SetPdnsID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ZoneUpdateOne) SetName(v string) *ZoneUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableName(v *string) *ZoneUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ZoneUpdateOne) SetKind(v zone.Kind) *ZoneUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableKind(v *zone.Kind) *ZoneUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetMasters sets the "masters" field.
func (_u *ZoneUpdateOne) SetMasters(v string) *ZoneUpdateOne {
	_u.mutation.SetMasters(v)
	return _u
}

// SetNillableMasters sets the "masters" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableMasters(v *string) *ZoneUpdateOne {
	if v != nil {
		_u.SetMasters(*v)
	}
	return _u
}

// ClearMasters clears the value of the "masters" field.
func (_u *ZoneUpdateOne) ClearMasters() *ZoneUpdateOne {
	_u.mutation.ClearMasters()
	return _u
}

// SetDnssecEnabled sets the "dnssec_enabled" field.
func (_u *ZoneUpdateOne) SetDnssecEnabled(v bool) *ZoneUpdateOne {
	_u.mutation.SetDnssecEnabled(v)
	return _u
}

// SetNillableDnssecEnabled sets the "dnssec_enabled" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableDnssecEnabled(v *bool) *ZoneUpdateOne {
	if v != nil {
		_u.SetDnssecEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ZoneUpdateOne) SetDescription(v string) *ZoneUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableDescription(v *string) *ZoneUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ZoneUpdateOne) ClearDescription() *ZoneUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *ZoneUpdateOne) SetTemplateID(v string) *ZoneUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *ZoneUpdateOne) SetNillableTemplateID(v *string) *ZoneUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// ClearTemplateID clears the value of the "template_id" field.
func (_u *ZoneUpdateOne) ClearTemplateID() *ZoneUpdateOne {
	_u.mutation.ClearTemplateID()
	return _u
}

// Mutation returns the ZoneMutation object of the builder.
func (_u *ZoneUpdateOne) Mutation() *ZoneMutation {
	return _u.mutation
}

// Where appends a list predicates to the ZoneUpdate builder.
func (_u *ZoneUpdateOne) Where(ps ...predicate.Zone) *ZoneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ZoneUpdateOne) Select(field string, fields ...string) *ZoneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Zone entity.
func (_u *ZoneUpdateOne) Save(ctx context.Context) (*Zone, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZoneUpdateOne) SaveX(ctx context.Context) *Zone {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ZoneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZoneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZoneUpdateOne) check() error {
	if v, ok := _u.mutation.PdnsID(); ok {
		if err := zone.PdnsIDValidator(v); err != nil {
			return &ValidationError{Name: "pdns_id", err: fmt.Errorf(`ent: validator failed for field "Zone.pdns_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := zone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Zone.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := zone.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Zone.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Masters(); ok {
		if err := zone.MastersValidator(v); err != nil {
			return &ValidationError{Name: "masters", err: fmt.Errorf(`ent: validator failed for field "Zone.masters": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := zone.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Zone.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := zone.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "Zone.template_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ZoneUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ZoneUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ZoneUpdateOne) sqlSave(ctx context.Context) (_node *Zone, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zone.Table, zone.Columns, sqlgraph.NewFieldSpec(zone.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Zone.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, zone.FieldID)
		for _, f := range fields {
			if !zone.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != zone.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(zone.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(zone.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(zone.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(zone.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(zone.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(zone.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(zone.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(zone.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(zone.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PdnsID(); ok {
		_spec.SetField(zone.FieldPdnsID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(zone.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(zone.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Masters(); ok {
		_spec.SetField(zone.FieldMasters, field.TypeString, value)
	}
	if _u.mutation.MastersCleared() {
		_spec.ClearField(zone.FieldMasters, field.TypeString)
	}
	if value, ok := _u.mutation.DnssecEnabled(); ok {
		_spec.SetField(zone.FieldDnssecEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(zone.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(zone.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(zone.FieldTemplateID, field.TypeString, value)
	}
	if _u.mutation.TemplateIDCleared() {
		_spec.ClearField(zone.FieldTemplateID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Zone{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
