// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zonetemplate"
)

// ZoneTemplateCreate is the builder for creating a ZoneTemplate entity.
type ZoneTemplateCreate struct {
	config
	mutation *ZoneTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *ZoneTemplateCreate) SetCreateBy(v uint32) *ZoneTemplateCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *ZoneTemplateCreate) SetNillableCreateBy(v *uint32) *ZoneTemplateCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ZoneTemplateCreate) SetCreateTime(v time.Time) *ZoneTemplateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ZoneTemplateCreate) SetNillableCreateTime(v *time.Time) *ZoneTemplateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ZoneTemplateCreate) SetUpdateTime(v time.Time) *ZoneTemplateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ZoneTemplateCreate) SetNillableUpdateTime(v *time.Time) *ZoneTemplateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ZoneTemplateCreate) SetDeleteTime(v time.Time) *ZoneTemplateCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ZoneTemplateCreate) SetNillableDeleteTime(v *time.Time) *ZoneTemplateCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ZoneTemplateCreate) SetTenantID(v uint32) *ZoneTemplateCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ZoneTemplateCreate) SetNillableTenantID(v *uint32) *ZoneTemplateCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ZoneTemplateCreate) SetName(v string) *ZoneTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ZoneTemplateCreate) SetDescription(v string) *ZoneTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ZoneTemplateCreate) SetNillableDescription(v *string) *ZoneTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRecords sets the "records" field.
func (_c *ZoneTemplateCreate) SetRecords(v []schema.TemplateRecordStanza) *ZoneTemplateCreate {
	_c.mutation.SetRecords(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ZoneTemplateCreate) SetID(v string) *ZoneTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ZoneTemplateMutation object of the builder.
func (_c *ZoneTemplateCreate) Mutation() *ZoneTemplateMutation {
	return _c.mutation
}

// Save creates the ZoneTemplate in the database.
func (_c *ZoneTemplateCreate) Save(ctx context.Context) (*ZoneTemplate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ZoneTemplateCreate) SaveX(ctx context.Context) *ZoneTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZoneTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZoneTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ZoneTemplateCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := zonetemplate.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ZoneTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ZoneTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := zonetemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := zonetemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := zonetemplate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ZoneTemplateCreate) sqlSave(ctx context.Context) (*ZoneTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ZoneTemplate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ZoneTemplateCreate) createSpec() (*ZoneTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &ZoneTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(zonetemplate.Table, sqlgraph.NewFieldSpec(zonetemplate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(zonetemplate.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(zonetemplate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(zonetemplate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(zonetemplate.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(zonetemplate.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(zonetemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(zonetemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Records(); ok {
		_spec.SetField(zonetemplate.FieldRecords, field.TypeJSON, value)
		_node.Records = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ZoneTemplate.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZoneTemplateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ZoneTemplateCreate) OnConflict(opts ...sql.ConflictOption) *ZoneTemplateUpsertOne {
	_c.conflict = opts
	return &ZoneTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ZoneTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ZoneTemplateCreate) OnConflictColumns(columns ...string) *ZoneTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ZoneTemplateUpsertOne{
		create: _c,
	}
}

type (
	// ZoneTemplateUpsertOne is the builder for "upsert"-ing
	//  one ZoneTemplate node.
	ZoneTemplateUpsertOne struct {
		create *ZoneTemplateCreate
	}

	// ZoneTemplateUpsert is the "OnConflict" setter.
	ZoneTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *ZoneTemplateUpsert) SetCreateBy(v uint32) *ZoneTemplateUpsert {
	u.Set(zonetemplate.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ZoneTemplateUpsert) UpdateCreateBy() *ZoneTemplateUpsert {
	u.SetExcluded(zonetemplate.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *ZoneTemplateUpsert) AddCreateBy(v uint32) *ZoneTemplateUpsert {
	u.Add(zonetemplate.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ZoneTemplateUpsert) ClearCreateBy() *ZoneTemplateUpsert {
	u.SetNull(zonetemplate.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ZoneTemplateUpsert) SetUpdateTime(v time.Time) *ZoneTemplateUpsert {
	u.Set(zonetemplate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ZoneTemplateUpsert) UpdateUpdateTime() *ZoneTemplateUpsert {
	u.SetExcluded(zonetemplate.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ZoneTemplateUpsert) ClearUpdateTime() *ZoneTemplateUpsert {
	u.SetNull(zonetemplate.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *ZoneTemplateUpsert) SetDeleteTime(v time.Time) *ZoneTemplateUpsert {
	u.Set(zonetemplate.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ZoneTemplateUpsert) UpdateDeleteTime() *ZoneTemplateUpsert {
	u.SetExcluded(zonetemplate.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ZoneTemplateUpsert) ClearDeleteTime() *ZoneTemplateUpsert {
	u.SetNull(zonetemplate.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *ZoneTemplateUpsert) SetName(v string) *ZoneTemplateUpsert {
	u.Set(zonetemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ZoneTemplateUpsert) UpdateName() *ZoneTemplateUpsert {
	u.SetExcluded(zonetemplate.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ZoneTemplateUpsert) SetDescription(v string) *ZoneTemplateUpsert {
	u.Set(zonetemplate.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ZoneTemplateUpsert) UpdateDescription() *ZoneTemplateUpsert {
	u.SetExcluded(zonetemplate.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ZoneTemplateUpsert) ClearDescription() *ZoneTemplateUpsert {
	u.SetNull(zonetemplate.FieldDescription)
	return u
}

// SetRecords sets the "records" field.
func (u *ZoneTemplateUpsert) SetRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpsert {
	u.Set(zonetemplate.FieldRecords, v)
	return u
}

// UpdateRecords sets the "records" field to the value that was provided on create.
func (u *ZoneTemplateUpsert) UpdateRecords() *ZoneTemplateUpsert {
	u.SetExcluded(zonetemplate.FieldRecords)
	return u
}

// ClearRecords clears the value of the "records" field.
func (u *ZoneTemplateUpsert) ClearRecords() *ZoneTemplateUpsert {
	u.SetNull(zonetemplate.FieldRecords)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ZoneTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(zonetemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ZoneTemplateUpsertOne) UpdateNewValues() *ZoneTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(zonetemplate.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(zonetemplate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(zonetemplate.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ZoneTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ZoneTemplateUpsertOne) Ignore() *ZoneTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZoneTemplateUpsertOne) DoNothing() *ZoneTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZoneTemplateCreate.OnConflict
// documentation for more info.
func (u *ZoneTemplateUpsertOne) Update(set func(*ZoneTemplateUpsert)) *ZoneTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZoneTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ZoneTemplateUpsertOne) SetCreateBy(v uint32) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ZoneTemplateUpsertOne) AddCreateBy(v uint32) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ZoneTemplateUpsertOne) UpdateCreateBy() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ZoneTemplateUpsertOne) ClearCreateBy() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ZoneTemplateUpsertOne) SetUpdateTime(v time.Time) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ZoneTemplateUpsertOne) UpdateUpdateTime() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ZoneTemplateUpsertOne) ClearUpdateTime() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ZoneTemplateUpsertOne) SetDeleteTime(v time.Time) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ZoneTemplateUpsertOne) UpdateDeleteTime() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ZoneTemplateUpsertOne) ClearDeleteTime() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *ZoneTemplateUpsertOne) SetName(v string) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ZoneTemplateUpsertOne) UpdateName() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ZoneTemplateUpsertOne) SetDescription(v string) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ZoneTemplateUpsertOne) UpdateDescription() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ZoneTemplateUpsertOne) ClearDescription() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearDescription()
	})
}

// SetRecords sets the "records" field.
func (u *ZoneTemplateUpsertOne) SetRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetRecords(v)
	})
}

// UpdateRecords sets the "records" field to the value that was provided on create.
func (u *ZoneTemplateUpsertOne) UpdateRecords() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateRecords()
	})
}

// ClearRecords clears the value of the "records" field.
func (u *ZoneTemplateUpsertOne) ClearRecords() *ZoneTemplateUpsertOne {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearRecords()
	})
}

// Exec executes the query.
func (u *ZoneTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZoneTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZoneTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ZoneTemplateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ZoneTemplateUpsertOne.ID is not supported by MySQL driver. Use ZoneTemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ZoneTemplateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ZoneTemplateCreateBulk is the builder for creating many ZoneTemplate entities in bulk.
type ZoneTemplateCreateBulk struct {
	config
	err      error
	builders []*ZoneTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the ZoneTemplate entities in the database.
func (_c *ZoneTemplateCreateBulk) Save(ctx context.Context) ([]*ZoneTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ZoneTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ZoneTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ZoneTemplateCreateBulk) SaveX(ctx context.Context) []*ZoneTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZoneTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZoneTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ZoneTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZoneTemplateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ZoneTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *ZoneTemplateUpsertBulk {
	_c.conflict = opts
	return &ZoneTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ZoneTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ZoneTemplateCreateBulk) OnConflictColumns(columns ...string) *ZoneTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ZoneTemplateUpsertBulk{
		create: _c,
	}
}

// ZoneTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of ZoneTemplate nodes.
type ZoneTemplateUpsertBulk struct {
	create *ZoneTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ZoneTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(zonetemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ZoneTemplateUpsertBulk) UpdateNewValues() *ZoneTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(zonetemplate.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(zonetemplate.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(zonetemplate.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ZoneTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ZoneTemplateUpsertBulk) Ignore() *ZoneTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZoneTemplateUpsertBulk) DoNothing() *ZoneTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZoneTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *ZoneTemplateUpsertBulk) Update(set func(*ZoneTemplateUpsert)) *ZoneTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZoneTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ZoneTemplateUpsertBulk) SetCreateBy(v uint32) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ZoneTemplateUpsertBulk) AddCreateBy(v uint32) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ZoneTemplateUpsertBulk) UpdateCreateBy() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ZoneTemplateUpsertBulk) ClearCreateBy() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ZoneTemplateUpsertBulk) SetUpdateTime(v time.Time) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ZoneTemplateUpsertBulk) UpdateUpdateTime() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ZoneTemplateUpsertBulk) ClearUpdateTime() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ZoneTemplateUpsertBulk) SetDeleteTime(v time.Time) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ZoneTemplateUpsertBulk) UpdateDeleteTime() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ZoneTemplateUpsertBulk) ClearDeleteTime() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *ZoneTemplateUpsertBulk) SetName(v string) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ZoneTemplateUpsertBulk) UpdateName() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ZoneTemplateUpsertBulk) SetDescription(v string) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ZoneTemplateUpsertBulk) UpdateDescription() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ZoneTemplateUpsertBulk) ClearDescription() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearDescription()
	})
}

// SetRecords sets the "records" field.
func (u *ZoneTemplateUpsertBulk) SetRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.SetRecords(v)
	})
}

// UpdateRecords sets the "records" field to the value that was provided on create.
func (u *ZoneTemplateUpsertBulk) UpdateRecords() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.UpdateRecords()
	})
}

// ClearRecords clears the value of the "records" field.
func (u *ZoneTemplateUpsertBulk) ClearRecords() *ZoneTemplateUpsertBulk {
	return u.Update(func(s *ZoneTemplateUpsert) {
		s.ClearRecords()
	})
}

// Exec executes the query.
func (u *ZoneTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ZoneTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZoneTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZoneTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
