// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zonetemplate"
)

// ZoneTemplateDelete is the builder for deleting a ZoneTemplate entity.
type ZoneTemplateDelete struct {
	config
	hooks    []Hook
	mutation *ZoneTemplateMutation
}

// Where appends a list predicates to the ZoneTemplateDelete builder.
func (_d *ZoneTemplateDelete) Where(ps ...predicate.ZoneTemplate) *ZoneTemplateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ZoneTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ZoneTemplateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ZoneTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(zonetemplate.Table, sqlgraph.NewFieldSpec(zonetemplate.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ZoneTemplateDeleteOne is the builder for deleting a single ZoneTemplate entity.
type ZoneTemplateDeleteOne struct {
	_d *ZoneTemplateDelete
}

// Where appends a list predicates to the ZoneTemplateDelete builder.
func (_d *ZoneTemplateDeleteOne) Where(ps ...predicate.ZoneTemplate) *ZoneTemplateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ZoneTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{zonetemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ZoneTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
