// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zonetemplate"
)

// ZoneTemplateUpdate is the builder for updating ZoneTemplate entities.
type ZoneTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *ZoneTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ZoneTemplateUpdate builder.
func (_u *ZoneTemplateUpdate) Where(ps ...predicate.ZoneTemplate) *ZoneTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *ZoneTemplateUpdate) SetCreateBy(v uint32) *ZoneTemplateUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ZoneTemplateUpdate) SetNillableCreateBy(v *uint32) *ZoneTemplateUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ZoneTemplateUpdate) AddCreateBy(v int32) *ZoneTemplateUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ZoneTemplateUpdate) ClearCreateBy() *ZoneTemplateUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ZoneTemplateUpdate) SetUpdateTime(v time.Time) *ZoneTemplateUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ZoneTemplateUpdate) SetNillableUpdateTime(v *time.Time) *ZoneTemplateUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ZoneTemplateUpdate) ClearUpdateTime() *ZoneTemplateUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ZoneTemplateUpdate) SetDeleteTime(v time.Time) *ZoneTemplateUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ZoneTemplateUpdate) SetNillableDeleteTime(v *time.Time) *ZoneTemplateUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ZoneTemplateUpdate) ClearDeleteTime() *ZoneTemplateUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ZoneTemplateUpdate) SetName(v string) *ZoneTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ZoneTemplateUpdate) SetNillableName(v *string) *ZoneTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ZoneTemplateUpdate) SetDescription(v string) *ZoneTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ZoneTemplateUpdate) SetNillableDescription(v *string) *ZoneTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ZoneTemplateUpdate) ClearDescription() *ZoneTemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRecords sets the "records" field.
func (_u *ZoneTemplateUpdate) SetRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpdate {
	_u.mutation.SetRecords(v)
	return _u
}

// AppendRecords appends value to the "records" field.
func (_u *ZoneTemplateUpdate) AppendRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpdate {
	_u.mutation.AppendRecords(v)
	return _u
}

// ClearRecords clears the value of the "records" field.
func (_u *ZoneTemplateUpdate) ClearRecords() *ZoneTemplateUpdate {
	_u.mutation.ClearRecords()
	return _u
}

// Mutation returns the ZoneTemplateMutation object of the builder.
func (_u *ZoneTemplateUpdate) Mutation() *ZoneTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ZoneTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZoneTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ZoneTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZoneTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZoneTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := zonetemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := zonetemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.description": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ZoneTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ZoneTemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ZoneTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zonetemplate.Table, zonetemplate.Columns, sqlgraph.NewFieldSpec(zonetemplate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(zonetemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(zonetemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(zonetemplate.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(zonetemplate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(zonetemplate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(zonetemplate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(zonetemplate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(zonetemplate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(zonetemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(zonetemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(zonetemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(zonetemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Records(); ok {
		_spec.SetField(zonetemplate.FieldRecords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRecords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, zonetemplate.FieldRecords, value)
		})
	}
	if _u.mutation.RecordsCleared() {
		_spec.ClearField(zonetemplate.FieldRecords, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zonetemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ZoneTemplateUpdateOne is the builder for updating a single ZoneTemplate entity.
type ZoneTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ZoneTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *ZoneTemplateUpdateOne) SetCreateBy(v uint32) *ZoneTemplateUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ZoneTemplateUpdateOne) SetNillableCreateBy(v *uint32) *ZoneTemplateUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ZoneTemplateUpdateOne) AddCreateBy(v int32) *ZoneTemplateUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ZoneTemplateUpdateOne) ClearCreateBy() *ZoneTemplateUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ZoneTemplateUpdateOne) SetUpdateTime(v time.Time) *ZoneTemplateUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ZoneTemplateUpdateOne) SetNillableUpdateTime(v *time.Time) *ZoneTemplateUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ZoneTemplateUpdateOne) ClearUpdateTime() *ZoneTemplateUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ZoneTemplateUpdateOne) SetDeleteTime(v time.Time) *ZoneTemplateUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ZoneTemplateUpdateOne) SetNillableDeleteTime(v *time.Time) *ZoneTemplateUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ZoneTemplateUpdateOne) ClearDeleteTime() *ZoneTemplateUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ZoneTemplateUpdateOne) SetName(v string) *ZoneTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ZoneTemplateUpdateOne) SetNillableName(v *string) *ZoneTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ZoneTemplateUpdateOne) SetDescription(v string) *ZoneTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ZoneTemplateUpdateOne) SetNillableDescription(v *string) *ZoneTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ZoneTemplateUpdateOne) ClearDescription() *ZoneTemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRecords sets the "records" field.
func (_u *ZoneTemplateUpdateOne) SetRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpdateOne {
	_u.mutation.SetRecords(v)
	return _u
}

// AppendRecords appends value to the "records" field.
func (_u *ZoneTemplateUpdateOne) AppendRecords(v []schema.TemplateRecordStanza) *ZoneTemplateUpdateOne {
	_u.mutation.AppendRecords(v)
	return _u
}

// ClearRecords clears the value of the "records" field.
func (_u *ZoneTemplateUpdateOne) ClearRecords() *ZoneTemplateUpdateOne {
	_u.mutation.ClearRecords()
	return _u
}

// Mutation returns the ZoneTemplateMutation object of the builder.
func (_u *ZoneTemplateUpdateOne) Mutation() *ZoneTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ZoneTemplateUpdate builder.
func (_u *ZoneTemplateUpdateOne) Where(ps ...predicate.ZoneTemplate) *ZoneTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ZoneTemplateUpdateOne) Select(field string, fields ...string) *ZoneTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ZoneTemplate entity.
func (_u *ZoneTemplateUpdateOne) Save(ctx context.Context) (*ZoneTemplate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZoneTemplateUpdateOne) SaveX(ctx context.Context) *ZoneTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ZoneTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZoneTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZoneTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := zonetemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := zonetemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ZoneTemplate.description": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ZoneTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ZoneTemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ZoneTemplateUpdateOne) sqlSave(ctx context.Context) (_node *ZoneTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zonetemplate.Table, zonetemplate.Columns, sqlgraph.NewFieldSpec(zonetemplate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ZoneTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, zonetemplate.FieldID)
		for _, f := range fields {
			if !zonetemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != zonetemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(zonetemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(zonetemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(zonetemplate.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(zonetemplate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(zonetemplate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(zonetemplate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(zonetemplate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(zonetemplate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(zonetemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(zonetemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(zonetemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(zonetemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Records(); ok {
		_spec.SetField(zonetemplate.FieldRecords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRecords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, zonetemplate.FieldRecords, value)
		})
	}
	if _u.mutation.RecordsCleared() {
		_spec.ClearField(zonetemplate.FieldRecords, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ZoneTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zonetemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
