// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/zone"
)

// ZoneCreate is the builder for creating a Zone entity.
type ZoneCreate struct {
	config
	mutation *ZoneMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *ZoneCreate) SetCreateBy(v uint32) *ZoneCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableCreateBy(v *uint32) *ZoneCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ZoneCreate) SetCreateTime(v time.Time) *ZoneCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableCreateTime(v *time.Time) *ZoneCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ZoneCreate) SetUpdateTime(v time.Time) *ZoneCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableUpdateTime(v *time.Time) *ZoneCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ZoneCreate) SetDeleteTime(v time.Time) *ZoneCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableDeleteTime(v *time.Time) *ZoneCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ZoneCreate) SetTenantID(v uint32) *ZoneCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableTenantID(v *uint32) *ZoneCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetPdnsID sets the "pdns_id" field.
func (_c *ZoneCreate) SetPdnsID(v string) *ZoneCreate {
	_c.mutation.SetPdnsID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ZoneCreate) SetName(v string) *ZoneCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ZoneCreate) SetKind(v zone.Kind) *ZoneCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableKind(v *zone.Kind) *ZoneCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetMasters sets the "masters" field.
func (_c *ZoneCreate) SetMasters(v string) *ZoneCreate {
	_c.mutation.SetMasters(v)
	return _c
}

// SetNillableMasters sets the "masters" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableMasters(v *string) *ZoneCreate {
	if v != nil {
		_c.SetMasters(*v)
	}
	return _c
}

// SetDnssecEnabled sets the "dnssec_enabled" field.
func (_c *ZoneCreate) SetDnssecEnabled(v bool) *ZoneCreate {
	_c.mutation.SetDnssecEnabled(v)
	return _c
}

// SetNillableDnssecEnabled sets the "dnssec_enabled" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableDnssecEnabled(v *bool) *ZoneCreate {
	if v != nil {
		_c.SetDnssecEnabled(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ZoneCreate) SetDescription(v string) *ZoneCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableDescription(v *string) *ZoneCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *ZoneCreate) SetTemplateID(v string) *ZoneCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableTemplateID(v *string) *ZoneCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ZoneCreate) SetID(v string) *ZoneCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ZoneMutation object of the builder.
func (_c *ZoneCreate) Mutation() *ZoneMutation {
	return _c.mutation
}

// Save creates the Zone in the database.
func (_c *ZoneCreate) Save(ctx context.Context) (*Zone, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ZoneCreate) SaveX(ctx context.Context) *Zone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ZoneCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := zone.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := zone.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.DnssecEnabled(); !ok {
		v := zone.DefaultDnssecEnabled
		_c.mutation.SetDnssecEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ZoneCreate) check() error {
	if _, ok := _c.mutation.PdnsID(); !ok {
		return &ValidationError{Name: "pdns_id", err: errors.New(`ent: missing required field "Zone.pdns_id"`)}
	}
	if v, ok := _c.mutation.PdnsID(); ok {
		if err := zone.PdnsIDValidator(v); err != nil {
			return &ValidationError{Name: "pdns_id", err: fmt.Errorf(`ent: validator failed for field "Zone.pdns_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Zone.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := zone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Zone.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Zone.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := zone.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Zone.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Masters(); ok {
		if err := zone.MastersValidator(v); err != nil {
			return &ValidationError{Name: "masters", err: fmt.Errorf(`ent: validator failed for field "Zone.masters": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DnssecEnabled(); !ok {
		return &ValidationError{Name: "dnssec_enabled", err: errors.New(`ent: missing required field "Zone.dnssec_enabled"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := zone.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Zone.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := zone.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "Zone.template_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := zone.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Zone.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ZoneCreate) sqlSave(ctx context.Context) (*Zone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Zone.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ZoneCreate) createSpec() (*Zone, *sqlgraph.CreateSpec) {
	var (
		_node = &Zone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(zone.Table, sqlgraph.NewFieldSpec(zone.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(zone.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(zone.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(zone.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(zone.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(zone.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.PdnsID(); ok {
		_spec.SetField(zone.FieldPdnsID, field.TypeString, value)
		_node.PdnsID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(zone.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(zone.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Masters(); ok {
		_spec.SetField(zone.FieldMasters, field.TypeString, value)
		_node.Masters = value
	}
	if value, ok := _c.mutation.DnssecEnabled(); ok {
		_spec.SetField(zone.FieldDnssecEnabled, field.TypeBool, value)
		_node.DnssecEnabled = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(zone.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(zone.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Zone.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZoneUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ZoneCreate) OnConflict(opts ...sql.ConflictOption) *ZoneUpsertOne {
	_c.conflict = opts
	return &ZoneUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Zone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ZoneCreate) OnConflictColumns(columns ...string) *ZoneUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ZoneUpsertOne{
		create: _c,
	}
}

type (
	// ZoneUpsertOne is the builder for "upsert"-ing
	//  one Zone node.
	ZoneUpsertOne struct {
		create *ZoneCreate
	}

	// ZoneUpsert is the "OnConflict" setter.
	ZoneUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *ZoneUpsert) SetCreateBy(v uint32) *ZoneUpsert {
	u.Set(zone.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateCreateBy() *ZoneUpsert {
	u.SetExcluded(zone.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *ZoneUpsert) AddCreateBy(v uint32) *ZoneUpsert {
	u.Add(zone.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ZoneUpsert) ClearCreateBy() *ZoneUpsert {
	u.SetNull(zone.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ZoneUpsert) SetUpdateTime(v time.Time) *ZoneUpsert {
	u.Set(zone.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateUpdateTime() *ZoneUpsert {
	u.SetExcluded(zone.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ZoneUpsert) ClearUpdateTime() *ZoneUpsert {
	u.SetNull(zone.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *ZoneUpsert) SetDeleteTime(v time.Time) *ZoneUpsert {
	u.Set(zone.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateDeleteTime() *ZoneUpsert {
	u.SetExcluded(zone.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ZoneUpsert) ClearDeleteTime() *ZoneUpsert {
	u.SetNull(zone.FieldDeleteTime)
	return u
}

// SetPdnsID sets the "pdns_id" field.
func (u *ZoneUpsert) SetPdnsID(v string) *ZoneUpsert {
	u.Set(zone.FieldPdnsID, v)
	return u
}

// UpdatePdnsID sets the "pdns_id" field to the value that was provided on create.
func (u *ZoneUpsert) UpdatePdnsID() *ZoneUpsert {
	u.SetExcluded(zone.FieldPdnsID)
	return u
}

// SetName sets the "name" field.
func (u *ZoneUpsert) SetName(v string) *ZoneUpsert {
	u.Set(zone.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateName() *ZoneUpsert {
	u.SetExcluded(zone.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *ZoneUpsert) SetKind(v zone.Kind) *ZoneUpsert {
	u.Set(zone.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateKind() *ZoneUpsert {
	u.SetExcluded(zone.FieldKind)
	return u
}

// SetMasters sets the "masters" field.
func (u *ZoneUpsert) SetMasters(v string) *ZoneUpsert {
	u.Set(zone.FieldMasters, v)
	return u
}

// UpdateMasters sets the "masters" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateMasters() *ZoneUpsert {
	u.SetExcluded(zone.FieldMasters)
	return u
}

// ClearMasters clears the value of the "masters" field.
func (u *ZoneUpsert) ClearMasters() *ZoneUpsert {
	u.SetNull(zone.FieldMasters)
	return u
}

// SetDnssecEnabled sets the "dnssec_enabled" field.
func (u *ZoneUpsert) SetDnssecEnabled(v bool) *ZoneUpsert {
	u.Set(zone.FieldDnssecEnabled, v)
	return u
}

// UpdateDnssecEnabled sets the "dnssec_enabled" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateDnssecEnabled() *ZoneUpsert {
	u.SetExcluded(zone.FieldDnssecEnabled)
	return u
}

// SetDescription sets the "description" field.
func (u *ZoneUpsert) SetDescription(v string) *ZoneUpsert {
	u.Set(zone.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateDescription() *ZoneUpsert {
	u.SetExcluded(zone.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ZoneUpsert) ClearDescription() *ZoneUpsert {
	u.SetNull(zone.FieldDescription)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *ZoneUpsert) SetTemplateID(v string) *ZoneUpsert {
	u.Set(zone.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *ZoneUpsert) UpdateTemplateID() *ZoneUpsert {
	u.SetExcluded(zone.FieldTemplateID)
	return u
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *ZoneUpsert) ClearTemplateID() *ZoneUpsert {
	u.SetNull(zone.FieldTemplateID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Zone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(zone.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ZoneUpsertOne) UpdateNewValues() *ZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(zone.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(zone.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(zone.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Zone.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ZoneUpsertOne) Ignore() *ZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZoneUpsertOne) DoNothing() *ZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZoneCreate.OnConflict
// documentation for more info.
func (u *ZoneUpsertOne) Update(set func(*ZoneUpsert)) *ZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ZoneUpsertOne) SetCreateBy(v uint32) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ZoneUpsertOne) AddCreateBy(v uint32) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateCreateBy() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ZoneUpsertOne) ClearCreateBy() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ZoneUpsertOne) SetUpdateTime(v time.Time) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateUpdateTime() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ZoneUpsertOne) ClearUpdateTime() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ZoneUpsertOne) SetDeleteTime(v time.Time) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateDeleteTime() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ZoneUpsertOne) ClearDeleteTime() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearDeleteTime()
	})
}

// SetPdnsID sets the "pdns_id" field.
func (u *ZoneUpsertOne) SetPdnsID(v string) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetPdnsID(v)
	})
}

// UpdatePdnsID sets the "pdns_id" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdatePdnsID() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdatePdnsID()
	})
}

// SetName sets the "name" field.
func (u *ZoneUpsertOne) SetName(v string) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateName() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *ZoneUpsertOne) SetKind(v zone.Kind) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateKind() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateKind()
	})
}

// SetMasters sets the "masters" field.
func (u *ZoneUpsertOne) SetMasters(v string) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetMasters(v)
	})
}

// UpdateMasters sets the "masters" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateMasters() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateMasters()
	})
}

// ClearMasters clears the value of the "masters" field.
func (u *ZoneUpsertOne) ClearMasters() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearMasters()
	})
}

// SetDnssecEnabled sets the "dnssec_enabled" field.
func (u *ZoneUpsertOne) SetDnssecEnabled(v bool) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetDnssecEnabled(v)
	})
}

// UpdateDnssecEnabled sets the "dnssec_enabled" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateDnssecEnabled() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateDnssecEnabled()
	})
}

// SetDescription sets the "description" field.
func (u *ZoneUpsertOne) SetDescription(v string) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateDescription() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ZoneUpsertOne) ClearDescription() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearDescription()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *ZoneUpsertOne) SetTemplateID(v string) *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *ZoneUpsertOne) UpdateTemplateID() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *ZoneUpsertOne) ClearTemplateID() *ZoneUpsertOne {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearTemplateID()
	})
}

// Exec executes the query.
func (u *ZoneUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZoneCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZoneUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ZoneUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ZoneUpsertOne.ID is not supported by MySQL driver. Use ZoneUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ZoneUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ZoneCreateBulk is the builder for creating many Zone entities in bulk.
type ZoneCreateBulk struct {
	config
	err      error
	builders []*ZoneCreate
	conflict []sql.ConflictOption
}

// Save creates the Zone entities in the database.
func (_c *ZoneCreateBulk) Save(ctx context.Context) ([]*Zone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Zone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ZoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ZoneCreateBulk) SaveX(ctx context.Context) []*Zone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Zone.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZoneUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ZoneCreateBulk) OnConflict(opts ...sql.ConflictOption) *ZoneUpsertBulk {
	_c.conflict = opts
	return &ZoneUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Zone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ZoneCreateBulk) OnConflictColumns(columns ...string) *ZoneUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ZoneUpsertBulk{
		create: _c,
	}
}

// ZoneUpsertBulk is the builder for "upsert"-ing
// a bulk of Zone nodes.
type ZoneUpsertBulk struct {
	create *ZoneCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Zone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(zone.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ZoneUpsertBulk) UpdateNewValues() *ZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(zone.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(zone.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(zone.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Zone.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ZoneUpsertBulk) Ignore() *ZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZoneUpsertBulk) DoNothing() *ZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZoneCreateBulk.OnConflict
// documentation for more info.
func (u *ZoneUpsertBulk) Update(set func(*ZoneUpsert)) *ZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ZoneUpsertBulk) SetCreateBy(v uint32) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ZoneUpsertBulk) AddCreateBy(v uint32) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateCreateBy() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ZoneUpsertBulk) ClearCreateBy() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ZoneUpsertBulk) SetUpdateTime(v time.Time) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateUpdateTime() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ZoneUpsertBulk) ClearUpdateTime() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ZoneUpsertBulk) SetDeleteTime(v time.Time) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateDeleteTime() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ZoneUpsertBulk) ClearDeleteTime() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearDeleteTime()
	})
}

// SetPdnsID sets the "pdns_id" field.
func (u *ZoneUpsertBulk) SetPdnsID(v string) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetPdnsID(v)
	})
}

// UpdatePdnsID sets the "pdns_id" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdatePdnsID() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdatePdnsID()
	})
}

// SetName sets the "name" field.
func (u *ZoneUpsertBulk) SetName(v string) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateName() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *ZoneUpsertBulk) SetKind(v zone.Kind) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateKind() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateKind()
	})
}

// SetMasters sets the "masters" field.
func (u *ZoneUpsertBulk) SetMasters(v string) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetMasters(v)
	})
}

// UpdateMasters sets the "masters" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateMasters() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateMasters()
	})
}

// ClearMasters clears the value of the "masters" field.
func (u *ZoneUpsertBulk) ClearMasters() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearMasters()
	})
}

// SetDnssecEnabled sets the "dnssec_enabled" field.
func (u *ZoneUpsertBulk) SetDnssecEnabled(v bool) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetDnssecEnabled(v)
	})
}

// UpdateDnssecEnabled sets the "dnssec_enabled" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateDnssecEnabled() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateDnssecEnabled()
	})
}

// SetDescription sets the "description" field.
func (u *ZoneUpsertBulk) SetDescription(v string) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateDescription() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ZoneUpsertBulk) ClearDescription() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearDescription()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *ZoneUpsertBulk) SetTemplateID(v string) *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *ZoneUpsertBulk) UpdateTemplateID() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *ZoneUpsertBulk) ClearTemplateID() *ZoneUpsertBulk {
	return u.Update(func(s *ZoneUpsert) {
		s.ClearTemplateID()
	})
}

// Exec executes the query.
func (u *ZoneUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ZoneCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZoneCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZoneUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
