// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DnsConfig is the predicate function for dnsconfig builders.
type DnsConfig func(*sql.Selector)

// Supermaster is the predicate function for supermaster builders.
type Supermaster func(*sql.Selector)

// Zone is the predicate function for zone builders.
type Zone func(*sql.Selector)

// ZoneTemplate is the predicate function for zonetemplate builders.
type ZoneTemplate func(*sql.Selector)
