// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DNSConfigColumns holds the columns for the "dns_config" table.
	DNSConfigColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "Fixed config key (global)"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "data", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "JSON-encoded {recursor, authoritative} configuration"},
	}
	// DNSConfigTable holds the schema information for the "dns_config" table.
	DNSConfigTable = &schema.Table{
		Name:       "dns_config",
		Columns:    DNSConfigColumns,
		PrimaryKey: []*schema.Column{DNSConfigColumns[0]},
	}
	// DNSSupermastersColumns holds the columns for the "dns_supermasters" table.
	DNSSupermastersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "ip", Type: field.TypeString, Size: 64, Comment: "Master IPv4/IPv6 address"},
		{Name: "nameserver", Type: field.TypeString, Size: 255, Comment: "Nameserver hostname (must match SOA of incoming zones)"},
		{Name: "account", Type: field.TypeString, Nullable: true, Size: 64, Comment: "Optional 'account' tag for grouping"},
	}
	// DNSSupermastersTable holds the schema information for the "dns_supermasters" table.
	DNSSupermastersTable = &schema.Table{
		Name:       "dns_supermasters",
		Columns:    DNSSupermastersColumns,
		PrimaryKey: []*schema.Column{DNSSupermastersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "supermaster_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DNSSupermastersColumns[5]},
			},
			{
				Name:    "supermaster_tenant_id_ip_nameserver",
				Unique:  true,
				Columns: []*schema.Column{DNSSupermastersColumns[5], DNSSupermastersColumns[6], DNSSupermastersColumns[7]},
			},
		},
	}
	// DNSZonesColumns holds the columns for the "dns_zones" table.
	DNSZonesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "pdns_id", Type: field.TypeString, Size: 255, Comment: "PowerDNS zone id (canonical, trailing dot)"},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Zone name (canonical)"},
		{Name: "kind", Type: field.TypeEnum, Comment: "PowerDNS zone kind", Enums: []string{"NATIVE", "MASTER", "SLAVE", "PRODUCER", "CONSUMER"}, Default: "NATIVE"},
		{Name: "masters", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Comma-separated master IPs for SLAVE zones"},
		{Name: "dnssec_enabled", Type: field.TypeBool, Comment: "Whether DNSSEC is enabled for this zone", Default: false},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Local description / notes"},
		{Name: "template_id", Type: field.TypeString, Nullable: true, Size: 36, Comment: "Optional reference to the ZoneTemplate used at creation"},
	}
	// DNSZonesTable holds the schema information for the "dns_zones" table.
	DNSZonesTable = &schema.Table{
		Name:       "dns_zones",
		Columns:    DNSZonesColumns,
		PrimaryKey: []*schema.Column{DNSZonesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "zone_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DNSZonesColumns[5]},
			},
			{
				Name:    "zone_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{DNSZonesColumns[5], DNSZonesColumns[7]},
			},
			{
				Name:    "zone_pdns_id",
				Unique:  false,
				Columns: []*schema.Column{DNSZonesColumns[6]},
			},
			{
				Name:    "zone_kind",
				Unique:  false,
				Columns: []*schema.Column{DNSZonesColumns[8]},
			},
		},
	}
	// DNSZoneTemplatesColumns holds the columns for the "dns_zone_templates" table.
	DNSZoneTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "Template name (unique per tenant)"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Template description"},
		{Name: "records", Type: field.TypeJSON, Nullable: true, Comment: "Record stanzas applied on zone creation"},
	}
	// DNSZoneTemplatesTable holds the schema information for the "dns_zone_templates" table.
	DNSZoneTemplatesTable = &schema.Table{
		Name:       "dns_zone_templates",
		Columns:    DNSZoneTemplatesColumns,
		PrimaryKey: []*schema.Column{DNSZoneTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "zonetemplate_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DNSZoneTemplatesColumns[5]},
			},
			{
				Name:    "zonetemplate_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{DNSZoneTemplatesColumns[5], DNSZoneTemplatesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DNSConfigTable,
		DNSSupermastersTable,
		DNSZonesTable,
		DNSZoneTemplatesTable,
	}
)

func init() {
	DNSConfigTable.Annotation = &entsql.Annotation{
		Table: "dns_config",
	}
	DNSSupermastersTable.Annotation = &entsql.Annotation{
		Table: "dns_supermasters",
	}
	DNSZonesTable.Annotation = &entsql.Annotation{
		Table: "dns_zones",
	}
	DNSZoneTemplatesTable.Annotation = &entsql.Annotation{
		Table: "dns_zone_templates",
	}
}
