// Code generated by ent, DO NOT EDIT.

package zone

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-dns/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Zone {
	return predicate.Zone(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Zone {
	return predicate.Zone(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldTenantID, v))
}

// PdnsID applies equality check predicate on the "pdns_id" field. It's identical to PdnsIDEQ.
func PdnsID(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldPdnsID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldName, v))
}

// Masters applies equality check predicate on the "masters" field. It's identical to MastersEQ.
func Masters(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldMasters, v))
}

// DnssecEnabled applies equality check predicate on the "dnssec_enabled" field. It's identical to DnssecEnabledEQ.
func DnssecEnabled(v bool) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldDnssecEnabled, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldDescription, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldTemplateID, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldTenantID))
}

// PdnsIDEQ applies the EQ predicate on the "pdns_id" field.
func PdnsIDEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldPdnsID, v))
}

// PdnsIDNEQ applies the NEQ predicate on the "pdns_id" field.
func PdnsIDNEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldPdnsID, v))
}

// PdnsIDIn applies the In predicate on the "pdns_id" field.
func PdnsIDIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldPdnsID, vs...))
}

// PdnsIDNotIn applies the NotIn predicate on the "pdns_id" field.
func PdnsIDNotIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldPdnsID, vs...))
}

// PdnsIDGT applies the GT predicate on the "pdns_id" field.
func PdnsIDGT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldPdnsID, v))
}

// PdnsIDGTE applies the GTE predicate on the "pdns_id" field.
func PdnsIDGTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldPdnsID, v))
}

// PdnsIDLT applies the LT predicate on the "pdns_id" field.
func PdnsIDLT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldPdnsID, v))
}

// PdnsIDLTE applies the LTE predicate on the "pdns_id" field.
func PdnsIDLTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldPdnsID, v))
}

// PdnsIDContains applies the Contains predicate on the "pdns_id" field.
func PdnsIDContains(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContains(FieldPdnsID, v))
}

// PdnsIDHasPrefix applies the HasPrefix predicate on the "pdns_id" field.
func PdnsIDHasPrefix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasPrefix(FieldPdnsID, v))
}

// PdnsIDHasSuffix applies the HasSuffix predicate on the "pdns_id" field.
func PdnsIDHasSuffix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasSuffix(FieldPdnsID, v))
}

// PdnsIDEqualFold applies the EqualFold predicate on the "pdns_id" field.
func PdnsIDEqualFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEqualFold(FieldPdnsID, v))
}

// PdnsIDContainsFold applies the ContainsFold predicate on the "pdns_id" field.
func PdnsIDContainsFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContainsFold(FieldPdnsID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldKind, vs...))
}

// MastersEQ applies the EQ predicate on the "masters" field.
func MastersEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldMasters, v))
}

// MastersNEQ applies the NEQ predicate on the "masters" field.
func MastersNEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldMasters, v))
}

// MastersIn applies the In predicate on the "masters" field.
func MastersIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldMasters, vs...))
}

// MastersNotIn applies the NotIn predicate on the "masters" field.
func MastersNotIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldMasters, vs...))
}

// MastersGT applies the GT predicate on the "masters" field.
func MastersGT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldMasters, v))
}

// MastersGTE applies the GTE predicate on the "masters" field.
func MastersGTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldMasters, v))
}

// MastersLT applies the LT predicate on the "masters" field.
func MastersLT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldMasters, v))
}

// MastersLTE applies the LTE predicate on the "masters" field.
func MastersLTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldMasters, v))
}

// MastersContains applies the Contains predicate on the "masters" field.
func MastersContains(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContains(FieldMasters, v))
}

// MastersHasPrefix applies the HasPrefix predicate on the "masters" field.
func MastersHasPrefix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasPrefix(FieldMasters, v))
}

// MastersHasSuffix applies the HasSuffix predicate on the "masters" field.
func MastersHasSuffix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasSuffix(FieldMasters, v))
}

// MastersIsNil applies the IsNil predicate on the "masters" field.
func MastersIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldMasters))
}

// MastersNotNil applies the NotNil predicate on the "masters" field.
func MastersNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldMasters))
}

// MastersEqualFold applies the EqualFold predicate on the "masters" field.
func MastersEqualFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEqualFold(FieldMasters, v))
}

// MastersContainsFold applies the ContainsFold predicate on the "masters" field.
func MastersContainsFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContainsFold(FieldMasters, v))
}

// DnssecEnabledEQ applies the EQ predicate on the "dnssec_enabled" field.
func DnssecEnabledEQ(v bool) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldDnssecEnabled, v))
}

// DnssecEnabledNEQ applies the NEQ predicate on the "dnssec_enabled" field.
func DnssecEnabledNEQ(v bool) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldDnssecEnabled, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContainsFold(FieldDescription, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v string) predicate.Zone {
	return predicate.Zone(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...string) predicate.Zone {
	return predicate.Zone(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v string) predicate.Zone {
	return predicate.Zone(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDContains applies the Contains predicate on the "template_id" field.
func TemplateIDContains(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContains(FieldTemplateID, v))
}

// TemplateIDHasPrefix applies the HasPrefix predicate on the "template_id" field.
func TemplateIDHasPrefix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasPrefix(FieldTemplateID, v))
}

// TemplateIDHasSuffix applies the HasSuffix predicate on the "template_id" field.
func TemplateIDHasSuffix(v string) predicate.Zone {
	return predicate.Zone(sql.FieldHasSuffix(FieldTemplateID, v))
}

// TemplateIDIsNil applies the IsNil predicate on the "template_id" field.
func TemplateIDIsNil() predicate.Zone {
	return predicate.Zone(sql.FieldIsNull(FieldTemplateID))
}

// TemplateIDNotNil applies the NotNil predicate on the "template_id" field.
func TemplateIDNotNil() predicate.Zone {
	return predicate.Zone(sql.FieldNotNull(FieldTemplateID))
}

// TemplateIDEqualFold applies the EqualFold predicate on the "template_id" field.
func TemplateIDEqualFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldEqualFold(FieldTemplateID, v))
}

// TemplateIDContainsFold applies the ContainsFold predicate on the "template_id" field.
func TemplateIDContainsFold(v string) predicate.Zone {
	return predicate.Zone(sql.FieldContainsFold(FieldTemplateID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Zone) predicate.Zone {
	return predicate.Zone(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Zone) predicate.Zone {
	return predicate.Zone(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Zone) predicate.Zone {
	return predicate.Zone(sql.NotPredicates(p))
}
