// Code generated by ent, DO NOT EDIT.

package zone

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the zone type in the database.
	Label = "zone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldPdnsID holds the string denoting the pdns_id field in the database.
	FieldPdnsID = "pdns_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldMasters holds the string denoting the masters field in the database.
	FieldMasters = "masters"
	// FieldDnssecEnabled holds the string denoting the dnssec_enabled field in the database.
	FieldDnssecEnabled = "dnssec_enabled"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// Table holds the table name of the zone in the database.
	Table = "dns_zones"
)

// Columns holds all SQL columns for zone fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldPdnsID,
	FieldName,
	FieldKind,
	FieldMasters,
	FieldDnssecEnabled,
	FieldDescription,
	FieldTemplateID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-dns/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// PdnsIDValidator is a validator for the "pdns_id" field. It is called by the builders before save.
	PdnsIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// MastersValidator is a validator for the "masters" field. It is called by the builders before save.
	MastersValidator func(string) error
	// DefaultDnssecEnabled holds the default value on creation for the "dnssec_enabled" field.
	DefaultDnssecEnabled bool
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	TemplateIDValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// KindNATIVE is the default value of the Kind enum.
const DefaultKind = KindNATIVE

// Kind values.
const (
	KindNATIVE   Kind = "NATIVE"
	KindMASTER   Kind = "MASTER"
	KindSLAVE    Kind = "SLAVE"
	KindPRODUCER Kind = "PRODUCER"
	KindCONSUMER Kind = "CONSUMER"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindNATIVE, KindMASTER, KindSLAVE, KindPRODUCER, KindCONSUMER:
		return nil
	default:
		return fmt.Errorf("zone: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Zone queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByPdnsID orders the results by the pdns_id field.
func ByPdnsID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdnsID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByMasters orders the results by the masters field.
func ByMasters(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMasters, opts...).ToFunc()
}

// ByDnssecEnabled orders the results by the dnssec_enabled field.
func ByDnssecEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDnssecEnabled, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}
