// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-dns/internal/cert"
	"github.com/go-tangra/go-tangra-dns/internal/data"
	"github.com/go-tangra/go-tangra-dns/internal/event"
	"github.com/go-tangra/go-tangra-dns/internal/metrics"
	"github.com/go-tangra/go-tangra-dns/internal/recursor"
	"github.com/go-tangra/go-tangra-dns/internal/server"
	"github.com/go-tangra/go-tangra-dns/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	zoneRepo := data.NewZoneRepo(context, entClient)
	zoneTemplateRepo := data.NewZoneTemplateRepo(context, entClient)
	client := data.NewPdnsClient(context)
	recursorClient := recursor.NewClient(context)
	zoneService := service.NewZoneService(context, zoneRepo, zoneTemplateRepo, client, recursorClient)
	recordService := service.NewRecordService(context, zoneRepo, client)
	zoneTemplateService := service.NewZoneTemplateService(context, zoneTemplateRepo)
	supermasterRepo := data.NewSupermasterRepo(context, entClient)
	supermasterService := service.NewSupermasterService(context, supermasterRepo, client)
	dnsConfigRepo := data.NewDnsConfigRepo(context, entClient)
	reconciler := recursor.NewReconciler(context, recursorClient, zoneRepo)
	configService := service.NewConfigService(context, dnsConfigRepo, reconciler)
	prometheusClient := data.NewPrometheusClient()
	dashboardService := service.NewDashboardService(context, prometheusClient)
	sqlBackupService := service.NewSqlBackupService(context)
	grpcServer := server.NewGRPCServer(context, certManager, collector, zoneService, recordService, zoneTemplateService, supermasterService, configService, dashboardService, sqlBackupService)
	httpServer := server.NewHTTPServer(context)
	redisClient, cleanup2, err := data.NewRedisClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handler := event.NewHandler(context, zoneRepo, client, recursorClient)
	subscriber := event.NewSubscriber(context, redisClient, handler)
	app := newApp(context, grpcServer, httpServer, subscriber, reconciler, configService)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
